// This file is auto-generated, don't edit it
import * as $dara from '@darabonba/typescript';


export class BindAuthToMachineResponseBodyDataBody extends $dara.Model {
  /**
   * @remarks
   * The number of servers that are successfully bound.
   * 
   * @example
   * 5
   */
  bindCount?: number;
  /**
   * @remarks
   * The number of insufficient core-based authorization quotas.
   * 
   * @example
   * 2
   */
  insufficientCoreCount?: number;
  /**
   * @remarks
   * The number of insufficient server-based authorization quotas.
   * 
   * @example
   * 1
   */
  insufficientEcsCount?: number;
  /**
   * @remarks
   * The request ID of Security Center.
   * 
   * @example
   * F799C1E4-D4C6-5964-A6D1-4BA9CCF105F2
   */
  requestId?: string;
  /**
   * @remarks
   * The status code of the binding result. Valid values:
   * 
   * 0: success.
   * 1: parameter error.
   * 2: insufficient server authorization quota.
   * 3: insufficient server core authorization quota.
   * 
   * @example
   * 2
   */
  resultCode?: number;
  /**
   * @remarks
   * The number of servers that are successfully unbound.
   * 
   * @example
   * 4
   */
  unBindCount?: number;
  static names(): { [key: string]: string } {
    return {
      bindCount: 'BindCount',
      insufficientCoreCount: 'InsufficientCoreCount',
      insufficientEcsCount: 'InsufficientEcsCount',
      requestId: 'RequestId',
      resultCode: 'ResultCode',
      unBindCount: 'UnBindCount',
    };
  }

  static types(): { [key: string]: any } {
    return {
      bindCount: 'number',
      insufficientCoreCount: 'number',
      insufficientEcsCount: 'number',
      requestId: 'string',
      resultCode: 'number',
      unBindCount: 'number',
    };
  }

  validate() {
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

export class BindAuthToMachineResponseBodyData extends $dara.Model {
  /**
   * @remarks
   * The message body.
   */
  body?: BindAuthToMachineResponseBodyDataBody;
  static names(): { [key: string]: string } {
    return {
      body: 'Body',
    };
  }

  static types(): { [key: string]: any } {
    return {
      body: BindAuthToMachineResponseBodyDataBody,
    };
  }

  validate() {
    if(this.body && typeof (this.body as any).validate === 'function') {
      (this.body as any).validate();
    }
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

export class BindAuthToMachineResponseBody extends $dara.Model {
  /**
   * @remarks
   * The error code returned if the call fails. For more information, see error codes.
   * 
   * @example
   * OK
   */
  code?: string;
  /**
   * @remarks
   * The data returned if the call is successful. For more information, see the following parameters.
   */
  data?: BindAuthToMachineResponseBodyData;
  /**
   * @remarks
   * message
   * 
   * @example
   * Successful
   */
  message?: string;
  /**
   * @remarks
   * The request ID generated by Alibaba Cloud for this request. You can use this ID to troubleshoot issues.
   * 
   * @example
   * BEE90F8C-EDC2-5394-953B-D07A121612B5
   */
  requestId?: string;
  /**
   * @remarks
   * Indicates whether the call is successful. true: The call is successful. false: The call fails.
   * 
   * @example
   * True
   */
  success?: boolean;
  static names(): { [key: string]: string } {
    return {
      code: 'Code',
      data: 'Data',
      message: 'Message',
      requestId: 'RequestId',
      success: 'Success',
    };
  }

  static types(): { [key: string]: any } {
    return {
      code: 'string',
      data: BindAuthToMachineResponseBodyData,
      message: 'string',
      requestId: 'string',
      success: 'boolean',
    };
  }

  validate() {
    if(this.data && typeof (this.data as any).validate === 'function') {
      (this.data as any).validate();
    }
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

