// This file is auto-generated, don't edit it
import * as $dara from '@darabonba/typescript';


export class UpdateInstanceServerlessSwitchRequest extends $dara.Model {
  /**
   * @remarks
   * The client token that is used to ensure the idempotence of the request. The value of this parameter is generated by the client and must be unique among different requests. The token can contain only ASCII characters and cannot exceed 64 characters in length.
   * 
   * @example
   * CCBB1225-C392-480E-8C7F-D09AB2CD2***
   */
  clientToken?: string;
  /**
   * @remarks
   * The instance ID.
   * 
   * This parameter is required.
   * 
   * @example
   * amqp-cn-v0h1kb9nu***
   */
  instanceId?: string;
  /**
   * @remarks
   * The serverless elastic capability.
   * 
   * - true (enabled): The maximum TPS of the instance is increased to the base TPS multiplied by a factor (1.5x for Professional Edition, 2x for Enterprise/Platinum Edition).
   * 
   * - false (disabled): The maximum TPS of the instance is restored to the original base TPS.
   * 
   * @example
   * true
   */
  serverlessSwitch?: boolean;
  static names(): { [key: string]: string } {
    return {
      clientToken: 'ClientToken',
      instanceId: 'InstanceId',
      serverlessSwitch: 'ServerlessSwitch',
    };
  }

  static types(): { [key: string]: any } {
    return {
      clientToken: 'string',
      instanceId: 'string',
      serverlessSwitch: 'boolean',
    };
  }

  validate() {
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

