// This file is auto-generated, don't edit it
import * as $dara from '@darabonba/typescript';


export class PauseEventStreamingResponseBody extends $dara.Model {
  /**
   * @remarks
   * The response code. Success: The request was successful. Other: An error code is returned. For more information about error codes, see Error codes.
   * 
   * @example
   * Success
   */
  code?: string;
  /**
   * @remarks
   * The error message.
   * 
   * @example
   * The event streaming [xxxx] not existed!
   */
  message?: string;
  /**
   * @remarks
   * The unique identifier generated by Alibaba Cloud for this request.
   * 
   * @example
   * 72ce027c-546a-4231-9cf6-ec58766027f9
   */
  requestId?: string;
  /**
   * @remarks
   * Indicates whether the operation was successful. The value true indicates success.
   * 
   * @example
   * true
   */
  success?: boolean;
  static names(): { [key: string]: string } {
    return {
      code: 'Code',
      message: 'Message',
      requestId: 'RequestId',
      success: 'Success',
    };
  }

  static types(): { [key: string]: any } {
    return {
      code: 'string',
      message: 'string',
      requestId: 'string',
      success: 'boolean',
    };
  }

  validate() {
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

