// This file is auto-generated, don't edit it
import * as $dara from '@darabonba/typescript';


export class CreateKeyRequest extends $dara.Model {
  /**
   * @remarks
   * The ID of the KMS instance.
   * 
   * > This parameter is required when you create a key for a KMS instance. This parameter is not required when you create a default key (master key).
   * 
   * @example
   * kst-bjj62d8f5e0sgtx8h****
   */
  DKMSInstanceId?: string;
  /**
   * @remarks
   * The description of the key.<br> The description can be 0 to 8,192 characters in length.<br>
   * 
   * @example
   * key description example
   */
  description?: string;
  /**
   * @remarks
   * Specifies whether to enable automatic key rotation. Valid values:
   * 
   * - true: enables automatic key rotation.
   * 
   * - false (default): disables automatic key rotation.
   * 
   * This parameter is valid only when the key management type of the key supports automatic rotation. For more information, see [Key rotation](https://help.aliyun.com/document_detail/2358146.html).
   * 
   * @example
   * true
   */
  enableAutomaticRotation?: boolean;
  /**
   * @remarks
   * The specification of the key. The valid values vary based on the key management type. For more information about key specifications, supported standards, and algorithms, see [Key management types and key specifications](https://help.aliyun.com/document_detail/480161.html).
   * 
   * > If you do not specify this parameter, the key specification is Aliyun_AES_256 by default.
   * 
   * @example
   * Aliyun_AES_256
   */
  keySpec?: string;
  /**
   * @remarks
   * The key storage location. This parameter is valid only when DKMSInstanceId is specified for a hardware key management instance. Valid values:
   * 
   * - HsmInternal (default): The key is stored in an HSM and does not support rotation.
   * 
   * - HsmEncryptedDatabase: The key is stored in a database.
   * 
   *   - Symmetric keys: Rotation is supported.
   * 
   *   - Asymmetric keys: Rotation is not supported.
   * 
   * @example
   * HsmInternal
   */
  keyStorageMechanism?: string;
  /**
   * @remarks
   * The usage of the key. Valid values:
   * 
   * - ENCRYPT/DECRYPT: encrypts and decrypts data.
   * 
   * - SIGN/VERIFY: generates and verifies digital signatures.
   * 
   * Default value: If the key supports signature verification, the default value is SIGN/VERIFY. Otherwise, the default value is ENCRYPT/DECRYPT.
   * 
   * @example
   * ENCRYPT/DECRYPT
   */
  keyUsage?: string;
  /**
   * @remarks
   * The source of the key material. Valid values:
   * 
   * - Aliyun_KMS (default): The key material is generated by Alibaba Cloud KMS.
   * 
   * - EXTERNAL: The key material is imported.
   * 
   * > * The value is case-sensitive.
   * 
   * - If you set this parameter to EXTERNAL, import key material. For more information, see [Import key material for a symmetric key](https://help.aliyun.com/document_detail/607841.html) or [Import key material for an asymmetric key](https://help.aliyun.com/document_detail/608827.html).
   * 
   * @example
   * Aliyun_KMS
   */
  origin?: string;
  /**
   * @remarks
   * The content of the key policy. The value is in the JSON format. The policy can be up to 32,768 bytes in length. For more information about key policies, see [Key policy overview](https://help.aliyun.com/document_detail/2716468.html). If you do not specify this parameter, the default credential policy is used.
   * 
   * A key policy contains the following content:
   * 
   * - Version: The version of the key policy. Only version 1 is supported.
   * 
   * - Statement: The statements of the key policy. Each key policy contains one or more statements.
   * 
   * The following is the format of a key policy:
   * 
   * ```
   * {
   *   "Version": "1",
   *   "Statement": [
   *     {
   *       "Sid": "Enable RAM User Permissions",
   *       "Effect": "Allow",
   *       "Principal": {
   *         "RAM": ["acs:ram::112890462****:root"]
   *       },
   *       "Action": [
   *         "kms:*"
   *       ],
   *       "Resource": [
   *         "*"
   *       ],
   *       "Condition": {
   *         "condition operator": {
   *           "condition key": "condition value"
   *         }
   *       }
   *     }
   *   ]
   * }
   * ```
   * 
   * Details about a statement:
   * 
   * - Sid: (Optional) The custom statement identifier. The identifier can be up to 128 characters in length and can contain uppercase letters (A-Z), lowercase letters (a-z), digits (0-9), and special characters, including underscores (_), forward slashes (/), plus signs (+), equal signs (=), periods (.), at signs (@), and hyphens (-).
   * 
   * - Effect: (Required) The effect of the policy statement. Valid values: Allow and Deny.
   * 
   * - Principal: (Required) The principal to which the permission is granted. Set this parameter to the current Alibaba Cloud account (the Alibaba Cloud account to which the key belongs), a RAM user or RAM role of the current Alibaba Cloud account, or a RAM user or RAM role of another Alibaba Cloud account.
   * 
   * - Action: (Required) The API operations that are allowed or denied. The value must start with "kms:". For a list of supported operations, see [Key policy overview](https://help.aliyun.com/document_detail/2716468.html). If you specify an operation that is not in the list, the setting does not take effect.
   * 
   * - Resource: (Required) The value can only be \\*, which indicates the current KMS key.
   * 
   * - Condition: (Optional) The conditions for the authorization to take effect. Use conditions to evaluate the context of an API request to determine whether to apply the policy statement. The format is `"Condition": {"condition operator": {"condition key": "condition value"}}`. For more information, see [Key policy overview](https://help.aliyun.com/document_detail/2716468.html).
   * 
   * > After granting permissions to a RAM user or RAM role of another Alibaba Cloud account, use that account to grant the RAM user or RAM role permissions to use the key in the RAM console. The RAM user or RAM role can use the key only after this is complete. For more information, see [Custom policies for Key Management Service](https://help.aliyun.com/document_detail/480682.html), [Grant permissions to a RAM user](https://help.aliyun.com/document_detail/116146.html), and [Grant permissions to a RAM role](https://help.aliyun.com/document_detail/116147.html).
   * 
   * @example
   * {"Statement":[{"Action":["kms:*"],"Effect":"Allow","Principal":{"RAM":["acs:ram::119285303511****:*"]},"Resource":["*"],"Sid":"kms default key policy"},{"Action":["kms:List*","kms:Describe*","kms:Create*","kms:Enable*","kms:Disable*","kms:Get*","kms:Set*","kms:Update*","kms:Delete*","kms:Cancel*","kms:TagResource","kms:UntagResource","kms:ImportKeyMaterial","kms:ScheduleKeyDeletion"],"Effect":"Allow","Principal":{"RAM":["acs:ram::119285303511****:user/for_test_policy"]},"Resource":["*"]}],"Version":"1"}
   */
  policy?: string;
  /**
   * @remarks
   * You do not need to specify this parameter. KMS automatically sets an appropriate protection level for your key.
   * 
   * The protection level of the key. Valid values:
   * 
   * - SOFTWARE
   * 
   * - HSM
   * 
   * > * If you specify DKMSInstanceId, this parameter is ignored. If the instance is a software key management instance, the protection level is SOFTWARE. If the instance is a hardware key management instance, the protection level is HSM.
   * 
   * - If you do not specify DKMSInstanceId, leave this parameter empty. KMS sets the protection level. If a managed HSM is available in the region, KMS sets this parameter to HSM. Otherwise, KMS sets this parameter to SOFTWARE. For more information, see [Managed HSM overview](https://help.aliyun.com/document_detail/125803.html).
   * 
   * @example
   * SOFTWARE
   */
  protectionLevel?: string;
  /**
   * @remarks
   * The automatic rotation period. The format is \\`integer[unit]\\`. \\`integer\\` indicates the length of the period. \\`unit\\` indicates the unit of time. Valid units: d (day), h (hour), m (minute), and s (second). For example, both 7d and 604800s represent a period of 7 days.
   * 
   * - If the key is a default key, the value is 365d.
   * 
   * - If the key is a software-protected key, the value can be from 7d to 365d.
   * 
   * - If the key is a hardware-protected key, automatic rotation is not supported.
   * 
   * > This parameter is required if you set EnableAutomaticRotation to true.
   * 
   * @example
   * 365d
   */
  rotationInterval?: string;
  /**
   * @remarks
   * The tags to bind to the key. Each tag consists of a key-value pair (Key:Value), which includes a tag key and a tag value.
   * 
   * Specify a maximum of 20 tags. To specify multiple tags, use the following format: `[{"TagKey":"key1","TagValue":"value1"},{"TagKey":"key2","TagValue":"value2"},...]`.
   * 
   * Each tag key and tag value can be up to 128 characters in length and can contain uppercase letters, lowercase letters, digits, forward slashes (/), backslashes (\\), underscores (_), hyphens (-), periods (.), plus signs (+), equal signs (=), colons (:), and at signs (@).
   * 
   * > The tag key cannot start with aliyun or acs:.
   * 
   * @example
   * [{"TagKey":"disk-encryption","TagValue":"true"}]
   */
  tags?: string;
  static names(): { [key: string]: string } {
    return {
      DKMSInstanceId: 'DKMSInstanceId',
      description: 'Description',
      enableAutomaticRotation: 'EnableAutomaticRotation',
      keySpec: 'KeySpec',
      keyStorageMechanism: 'KeyStorageMechanism',
      keyUsage: 'KeyUsage',
      origin: 'Origin',
      policy: 'Policy',
      protectionLevel: 'ProtectionLevel',
      rotationInterval: 'RotationInterval',
      tags: 'Tags',
    };
  }

  static types(): { [key: string]: any } {
    return {
      DKMSInstanceId: 'string',
      description: 'string',
      enableAutomaticRotation: 'boolean',
      keySpec: 'string',
      keyStorageMechanism: 'string',
      keyUsage: 'string',
      origin: 'string',
      policy: 'string',
      protectionLevel: 'string',
      rotationInterval: 'string',
      tags: 'string',
    };
  }

  validate() {
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

