// This file is auto-generated, don't edit it
import * as $dara from '@darabonba/typescript';


export class DeleteNetworkRuleResponseBody extends $dara.Model {
  /**
   * @remarks
   * The ID of the request. This ID is generated by Alibaba Cloud and is unique for each request. You can use it to troubleshoot issues.
   * 
   * @example
   * 3bf02f7a-015b-4f93-be0f-cc043fda2d4
   */
  requestId?: string;
  static names(): { [key: string]: string } {
    return {
      requestId: 'RequestId',
    };
  }

  static types(): { [key: string]: any } {
    return {
      requestId: 'string',
    };
  }

  validate() {
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

