// This file is auto-generated, don't edit it
import * as $dara from '@darabonba/typescript';


export class CreateImagePipelineRequestAdvancedOptions extends $dara.Model {
  /**
   * @remarks
   * Specifies whether to disable the automatic suffix for the destination image name. Valid values:
   * - disable: The automatic suffix is disabled.
   * 
   * @example
   * disable
   */
  imageNameSuffix?: string;
  /**
   * @remarks
   * Specifies whether to retain Cloud Assistant. During the build process, the system automatically installs Cloud Assistant on the intermediate instance to run commands. You can choose whether to retain Cloud Assistant in the destination image. Valid values:
   * - true: Cloud Assistant is retained.
   * - false: Cloud Assistant is not retained.
   * 
   * Default value: false.
   * > This setting does not affect Cloud Assistant that is already included in your image.
   * 
   * @example
   * true
   */
  retainCloudAssistant?: boolean;
  static names(): { [key: string]: string } {
    return {
      imageNameSuffix: 'ImageNameSuffix',
      retainCloudAssistant: 'RetainCloudAssistant',
    };
  }

  static types(): { [key: string]: any } {
    return {
      imageNameSuffix: 'string',
      retainCloudAssistant: 'boolean',
    };
  }

  validate() {
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

export class CreateImagePipelineRequestImageOptionsImageFeatures extends $dara.Model {
  /**
   * @remarks
   * Specifies whether the destination image supports NVMe. Valid values:
   * - supported: Instances created from this image support the NVMe protocol.
   * - unsupported: Instances created from this image do not support the NVMe protocol.
   * - auto: The system automatically detects whether your image has the NVMe driver installed. This detection occurs before the build phase. If you install or uninstall the NVMe driver during the build, the result may be inaccurate. Set this parameter to supported or unsupported based on your build content.
   * 
   * @example
   * auto
   */
  nvmeSupport?: string;
  static names(): { [key: string]: string } {
    return {
      nvmeSupport: 'NvmeSupport',
    };
  }

  static types(): { [key: string]: any } {
    return {
      nvmeSupport: 'string',
    };
  }

  validate() {
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

export class CreateImagePipelineRequestImageOptionsImageTags extends $dara.Model {
  /**
   * @remarks
   * The tag key. Valid values of N: 1 to 20. The tag key cannot be an empty string. The tag key can be up to 128 characters in length and cannot start with `aliyun` or `acs:`. The tag key cannot contain `http://` or `https://`.
   * 
   * @example
   * TestKey
   */
  key?: string;
  /**
   * @remarks
   * The tag value of the resource. Valid values of N: 1 to 20. The tag value can be an empty string. The tag value can be up to 128 characters in length and cannot start with `acs:`. The tag value cannot contain `http://` or `https://`.
   * 
   * @example
   * TestValue
   */
  value?: string;
  static names(): { [key: string]: string } {
    return {
      key: 'Key',
      value: 'Value',
    };
  }

  static types(): { [key: string]: any } {
    return {
      key: 'string',
      value: 'string',
    };
  }

  validate() {
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

export class CreateImagePipelineRequestImageOptions extends $dara.Model {
  /**
   * @remarks
   * The description. The description must be 2 to 256 characters in length and cannot start with `http://` or `https://`.
   * 
   * @example
   * This is description.
   */
  description?: string;
  /**
   * @remarks
   * The destination image family. The name must be 2 to 128 characters in length and must start with a letter or a Chinese character. The name cannot start with aliyun or acs:. The name cannot contain http:// or https://. The name can contain digits, colons (:), underscores (_), and hyphens (-).
   * 
   * @example
   * family
   */
  imageFamily?: string;
  /**
   * @remarks
   * The feature properties of the destination image.
   */
  imageFeatures?: CreateImagePipelineRequestImageOptionsImageFeatures;
  /**
   * @remarks
   * The prefix of the destination image name. The name must be 2 to 64 characters in length and must start with a letter or a Chinese character. The name cannot start with `http://` or `https://`. The name can contain Chinese characters, letters, digits, colons (:), underscores (_), periods (.), and hyphens (-).
   * 
   * The final complete image name is automatically generated by the system by concatenating the name prefix with the build task ID (`ExecutionId`) in the format of `{ImageName}_{ExecutionId}`.
   * 
   * @example
   * testImageName
   */
  imageName?: string;
  /**
   * @remarks
   * The tags of the destination image.
   */
  imageTags?: CreateImagePipelineRequestImageOptionsImageTags[];
  static names(): { [key: string]: string } {
    return {
      description: 'Description',
      imageFamily: 'ImageFamily',
      imageFeatures: 'ImageFeatures',
      imageName: 'ImageName',
      imageTags: 'ImageTags',
    };
  }

  static types(): { [key: string]: any } {
    return {
      description: 'string',
      imageFamily: 'string',
      imageFeatures: CreateImagePipelineRequestImageOptionsImageFeatures,
      imageName: 'string',
      imageTags: { 'type': 'array', 'itemType': CreateImagePipelineRequestImageOptionsImageTags },
    };
  }

  validate() {
    if(this.imageFeatures && typeof (this.imageFeatures as any).validate === 'function') {
      (this.imageFeatures as any).validate();
    }
    if(Array.isArray(this.imageTags)) {
      $dara.Model.validateArray(this.imageTags);
    }
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

export class CreateImagePipelineRequestImportImageOptionsDiskDeviceMappings extends $dara.Model {
  /**
   * @remarks
   * The size of the custom image after the image is imported.
   * 
   * The size consists of the system disk and data disks. Make sure that the system disk size is greater than or equal to the size of the imported image file. Valid values:
   * 
   * - When N=1, the system disk is specified. Valid values: 1 GiB to 2048 GiB.
   * - When N=2 to 17, data disks are specified. Valid values: 1 GiB to 2048 GiB.
   * 
   * After you upload the source image file to OSS, you can view the size of the image file in the OSS bucket.
   * 
   * @example
   * 40
   */
  diskImageSize?: number;
  /**
   * @remarks
   * The image format. Valid values:
   * 
   * - RAW.
   * - VHD.
   * - QCOW2.
   * 
   * Default value: empty, which indicates that Alibaba Cloud automatically detects the image format. The detected format prevails.
   * 
   * @example
   * RAW
   */
  format?: string;
  /**
   * @remarks
   * The OSS bucket in which the image file is stored.
   * 
   * @example
   * ecsimageos
   */
  OSSBucket?: string;
  /**
   * @remarks
   * The name (key) of the image file that is stored in the OSS bucket after the image is uploaded to OSS.
   * 
   * @example
   * CentOS_5.4_32.raw
   */
  OSSObject?: string;
  static names(): { [key: string]: string } {
    return {
      diskImageSize: 'DiskImageSize',
      format: 'Format',
      OSSBucket: 'OSSBucket',
      OSSObject: 'OSSObject',
    };
  }

  static types(): { [key: string]: any } {
    return {
      diskImageSize: 'number',
      format: 'string',
      OSSBucket: 'string',
      OSSObject: 'string',
    };
  }

  validate() {
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

export class CreateImagePipelineRequestImportImageOptionsFeatures extends $dara.Model {
  /**
   * @remarks
   * The metadata access mode of the image. Valid values:
   * 
   * - v1: When you create an ECS instance from this image, you cannot set the metadata access mode to "hardened mode only".
   * 
   * - v2: When you create an ECS instance from this image, you can set the metadata access mode to "hardened mode only".
   * 
   * Default value: v1.
   * 
   * @example
   * v2
   */
  imdsSupport?: string;
  /**
   * @remarks
   * Specifies whether the imported original image supports NVMe. Valid values:
   * - supported: Instances created from this image support the NVMe protocol.
   * - unsupported: Instances created from this image do not support the NVMe protocol.
   * 
   * Default value: unsupported.
   * 
   * @example
   * supported
   */
  nvmeSupport?: string;
  static names(): { [key: string]: string } {
    return {
      imdsSupport: 'ImdsSupport',
      nvmeSupport: 'NvmeSupport',
    };
  }

  static types(): { [key: string]: any } {
    return {
      imdsSupport: 'string',
      nvmeSupport: 'string',
    };
  }

  validate() {
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

export class CreateImagePipelineRequestImportImageOptionsImportImageTags extends $dara.Model {
  /**
   * @remarks
   * The tag key of the image.
   * 
   * @example
   * testKey
   */
  key?: string;
  /**
   * @remarks
   * The tag value of the image.
   * 
   * @example
   * testValue
   */
  value?: string;
  static names(): { [key: string]: string } {
    return {
      key: 'Key',
      value: 'Value',
    };
  }

  static types(): { [key: string]: any } {
    return {
      key: 'string',
      value: 'string',
    };
  }

  validate() {
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

export class CreateImagePipelineRequestImportImageOptions extends $dara.Model {
  /**
   * @remarks
   * The system architecture of the system disk when a data disk snapshot is used as the image for the system disk. Valid values:
   * 
   * - x86_64.
   * - arm64.
   * 
   * Default value: x86_64.
   * 
   * @example
   * x86_64
   */
  architecture?: string;
  /**
   * @remarks
   * The boot mode of the image. Valid values:
   * 
   * - BIOS: BIOS boot mode.
   * - UEFI: UEFI boot mode.
   * 
   * Default value: BIOS. If `Architecture=arm64`, the default value is UEFI, and only UEFI can be specified.
   * 
   * <notice>
   * 
   * To prevent instances from failing to start due to an unsupported boot mode, make sure that you understand the boot modes supported by the destination image before you set this parameter. For more information about image boot modes, see [Image boot modes](~~2244655#b9caa9b8bb1wf~~).
   * 
   * </notice>
   * 
   * @example
   * BIOS
   */
  bootMode?: string;
  /**
   * @remarks
   * The description of the imported image.
   * 
   * @example
   * This is description.
   */
  description?: string;
  /**
   * @remarks
   * The information about the custom image.
   * - When N=1, the system disk is specified.
   * - When N=2 to 17, data disks are specified.
   */
  diskDeviceMappings?: CreateImagePipelineRequestImportImageOptionsDiskDeviceMappings[];
  /**
   * @remarks
   * The image feature properties.
   */
  features?: CreateImagePipelineRequestImportImageOptionsFeatures;
  /**
   * @remarks
   * The name of the imported image.
   * 
   * @example
   * testImageName
   */
  imageName?: string;
  /**
   * @remarks
   * The tags of the image.
   */
  importImageTags?: CreateImagePipelineRequestImportImageOptionsImportImageTags[];
  /**
   * @remarks
   * The license type used to activate the operating system after the image is imported. Valid values:
   * 
   * - Auto: Alibaba Cloud detects the source operating system and assigns a license. In Auto mode, the system first searches for a license from an official Alibaba Cloud channel based on the `Platform` you specified and assigns it to the imported image. If no such license is available, the system switches to the BYOL (Bring Your Own License) method.
   * - Aliyun: A license from an official Alibaba Cloud channel is used based on the `Platform` you specified.
   * - BYOL: The license that comes with the source operating system is used. When you use BYOL, make sure that your license key supports use on Alibaba Cloud.
   * 
   * Default value: Auto.
   * 
   * @example
   * Auto
   */
  licenseType?: string;
  /**
   * @remarks
   * The operating system type. Valid values:
   * 
   * - windows.
   * - linux.
   * 
   * Default value: linux.
   * 
   * @example
   * linux
   */
  OSType?: string;
  /**
   * @remarks
   * The operating system version. Valid values:
   * - Aliyun
   * - Anolis
   * - CentOS
   * - Ubuntu
   * - CoreOS
   * - SUSE
   * - Debian
   * - OpenSUSE
   * - FreeBSD
   * - RedHat
   * - Kylin
   * - UOS
   * - Fedora
   * - Fedora CoreOS
   * - CentOS Stream
   * - AlmaLinux
   * - Rocky Linux
   * - Gentoo
   * - Customized Linux
   * - Others Linux
   * - Windows Server 2022
   * - Windows Server 2019
   * - Windows Server 2016
   * - Windows Server 2012
   * - Windows Server 2008
   * - Windows Server 2003
   * - Other Windows
   * 
   * Default value: Others Linux when the operating system type is Linux. Otherwise, the default value is Other Windows.
   * 
   * @example
   * Aliyun
   */
  platform?: string;
  /**
   * @remarks
   * **[Deprecated]** Use ImportImageOptions.RetentionStrategy instead.
   * 
   * @example
   * false
   */
  retainImportedImage?: boolean;
  /**
   * @remarks
   * The data retention policy for the imported image. Valid values:
   * 
   * - RetainOnlySuccessful: The image is retained only if the build succeeds.
   * 
   * - RetainOnlyFailed: The image is retained only if the build fails.
   * 
   * - RetainAlways: The image is always retained regardless of the build result.
   * 
   * - RetainNever: The image is never retained regardless of the build result.
   * 
   * Default value: RetainNever.
   * 
   * @example
   * RetainAlways
   */
  retentionStrategy?: string;
  /**
   * @remarks
   * The name of the RAM role used to import the image.
   */
  roleName?: string;
  static names(): { [key: string]: string } {
    return {
      architecture: 'Architecture',
      bootMode: 'BootMode',
      description: 'Description',
      diskDeviceMappings: 'DiskDeviceMappings',
      features: 'Features',
      imageName: 'ImageName',
      importImageTags: 'ImportImageTags',
      licenseType: 'LicenseType',
      OSType: 'OSType',
      platform: 'Platform',
      retainImportedImage: 'RetainImportedImage',
      retentionStrategy: 'RetentionStrategy',
      roleName: 'RoleName',
    };
  }

  static types(): { [key: string]: any } {
    return {
      architecture: 'string',
      bootMode: 'string',
      description: 'string',
      diskDeviceMappings: { 'type': 'array', 'itemType': CreateImagePipelineRequestImportImageOptionsDiskDeviceMappings },
      features: CreateImagePipelineRequestImportImageOptionsFeatures,
      imageName: 'string',
      importImageTags: { 'type': 'array', 'itemType': CreateImagePipelineRequestImportImageOptionsImportImageTags },
      licenseType: 'string',
      OSType: 'string',
      platform: 'string',
      retainImportedImage: 'boolean',
      retentionStrategy: 'string',
      roleName: 'string',
    };
  }

  validate() {
    if(Array.isArray(this.diskDeviceMappings)) {
      $dara.Model.validateArray(this.diskDeviceMappings);
    }
    if(this.features && typeof (this.features as any).validate === 'function') {
      (this.features as any).validate();
    }
    if(Array.isArray(this.importImageTags)) {
      $dara.Model.validateArray(this.importImageTags);
    }
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

export class CreateImagePipelineRequestTag extends $dara.Model {
  /**
   * @remarks
   * The tag key. Valid values of N: 1 to 20. The tag key cannot be an empty string. The tag key can be up to 128 characters in length and cannot start with `aliyun` or `acs:`. The tag key cannot contain `http://` or `https://`.
   * 
   * @example
   * TestKey
   */
  key?: string;
  /**
   * @remarks
   * The tag value. Valid values of N: 1 to 20. The tag value can be an empty string. The tag value can be up to 128 characters in length and cannot start with `acs:`. The tag value cannot contain `http://` or `https://`.
   * 
   * @example
   * TestValue
   */
  value?: string;
  static names(): { [key: string]: string } {
    return {
      key: 'Key',
      value: 'Value',
    };
  }

  static types(): { [key: string]: any } {
    return {
      key: 'string',
      value: 'string',
    };
  }

  validate() {
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

export class CreateImagePipelineRequest extends $dara.Model {
  /**
   * @remarks
   * The Alibaba Cloud account ID to which the destination image is shared through image sharing. Valid values of N: 1 to 20.
   * 
   * @example
   * 1234567890
   */
  addAccount?: number[];
  /**
   * @remarks
   * The advanced configuration.
   */
  advancedOptions?: CreateImagePipelineRequestAdvancedOptions;
  /**
   * @remarks
   * The source image.
   * - If `BaseImageType=IMAGE`, set this parameter to an image ID.
   * - If `BaseImageType=IMAGE_FAMILY`, set this parameter to an image family name.
   * - If `BaseImageType=OSS`, you do not need to set this parameter.
   * 
   * @example
   * m-bp67acfmxazb4p****
   */
  baseImage?: string;
  /**
   * @remarks
   * The type of the source image. Valid values:
   * 
   * - IMAGE: image.
   * - IMAGE_FAMILY: image family.
   * - OSS: OSS object.
   * 
   * This parameter is required.
   * 
   * @example
   * IMAGE
   */
  baseImageType?: string;
  /**
   * @remarks
   * The content of the image build template. The content size cannot exceed 16 KB. For more information about supported commands, see [Commands supported by Image Builder](https://help.aliyun.com/document_detail/200206.html).
   * 
   * @example
   * COMPONENT ic-bp12dvdzvr9k9*****
   * COMPONENT acs:ecs:cn-hangzhou:18689161186*****:imagecomponent/ComponentName/1.*.*
   */
  buildContent?: string;
  /**
   * @remarks
   * The client token that is used to ensure the idempotence of the request. You can use the client to generate the token, but make sure that the token is unique among different requests. The value of **ClientToken** can contain only ASCII characters and cannot exceed 64 characters in length. For more information, see [How to ensure idempotence](https://help.aliyun.com/document_detail/25693.html).
   * 
   * @example
   * 123e4567-e89b-12d3-a456-426655440000
   */
  clientToken?: string;
  /**
   * @remarks
   * Specifies whether to release the intermediate instance if the image fails to be built. Valid values:
   * 
   * - true: The intermediate instance is released.
   * - false: The intermediate instance is not released.
   * 
   * Default value: true.
   * 
   * > If the intermediate instance fails to start, the instance is not retained by default.
   * 
   * @example
   * true
   */
  deleteInstanceOnFailure?: boolean;
  /**
   * @remarks
   * The description. The description must be 2 to 256 characters in length and cannot start with `http://` or `https://`.
   * 
   * @example
   * This is description.
   */
  description?: string;
  /**
   * @remarks
   * The destination image family.
   * <notice>
   * **[Deprecated]** Use ImageOptions.ImageFamily instead.
   * </notice>
   * 
   * @example
   * family
   * 
   * @deprecated
   */
  imageFamily?: string;
  /**
   * @remarks
   * The prefix of the destination image name.
   * <notice>
   * **[Deprecated]** Use ImageOptions.ImageName instead.
   * </notice>
   * 
   * @example
   * testImageName
   * 
   * @deprecated
   */
  imageName?: string;
  /**
   * @remarks
   * The destination image properties.
   */
  imageOptions?: CreateImagePipelineRequestImageOptions;
  /**
   * @remarks
   * The properties and settings for importing an image. This parameter is required when `BaseImageType=OSS`.
   */
  importImageOptions?: CreateImagePipelineRequestImportImageOptions;
  /**
   * @remarks
   * The instance type. You can call [DescribeInstanceTypes](https://help.aliyun.com/document_detail/25620.html) to query different instance types.
   * 
   * If you do not specify this parameter, the instance type is automatically set based on the principle of minimum vCPUs and memory, subject to the inventory of the instance type. For example, the ecs.g6.large instance type is selected by default. If the inventory is insufficient, the ecs.g6.xlarge instance type is selected.
   * 
   * @example
   * ecs.g6.large
   */
  instanceType?: string;
  /**
   * @remarks
   * The outbound public bandwidth of the intermediate instance. Unit: Mbit/s. Valid values: 0 to 100.
   * 
   * Default value: 0.
   * 
   * @example
   * 0
   */
  internetMaxBandwidthOut?: number;
  /**
   * @remarks
   * The template name. The name must be 2 to 128 characters in length and must start with a letter or a Chinese character. The name cannot start with `http://` or `https://`. The name can contain Chinese characters, letters, digits, colons (:), underscores (_), periods (.), and hyphens (-).
   * 
   * > If you do not specify `Name`, the return value of `ImagePipelineId` is used by default.
   * 
   * @example
   * testImagePipeline
   */
  name?: string;
  /**
   * @remarks
   * Specifies whether the destination image supports NVMe.
   * <notice>
   * **[Deprecated]** Use ImageOptions.ImageFeatures.NvmeSupport instead.
   * </notice>
   * 
   * @example
   * auto
   * 
   * @deprecated
   */
  nvmeSupport?: string;
  ownerAccount?: string;
  ownerId?: number;
  /**
   * @remarks
   * The region ID. You can call [DescribeRegions](https://help.aliyun.com/document_detail/25609.html) to query the most recent region list.
   * 
   * This parameter is required.
   * 
   * @example
   * cn-hangzhou
   */
  regionId?: string;
  /**
   * @remarks
   * The image repair items.
   * 
   * - Repair items supported for Linux:
   *    - fstab: repairs disk mount configuration issues.
   *    - grub: repairs GRUB boot configuration issues.
   *    - dhcp: repairs network DHCP issues.
   *    - selinux: repairs Security-Enhanced Linux issues.
   *    - growpart: repairs root partition online auto-expansion issues.
   *    - cloudinit: installs the cloud-init initialization service.
   *    - aegis: installs the China Cloud Security Center Agent service.
   *    - nvme: repairs NVMe driver issues.
   *    - virtio: repairs virtio driver issues.
   *    - standardizedtimezone: repairs standardized time zone issues.
   * - Repair items supported for Windows:
   *    - bcd: repairs boot configuration data file issues.
   *    - hotfix: repairs Windows patch issues.
   *    - disk: repairs disk setting issues.
   *    - update: repairs Update process issues.
   *    - server: repairs service configuration issues.
   *    - bootmgr: repairs Windows Boot Manager issues.
   *    - vminit: repairs Windows initialization Agent issues.
   *    - osloader: repairs Windows OS Loader issues.
   *    - virtio: repairs virtio driver issues.
   *    - standardizedtimezone: repairs standardized time zone issues.
   */
  repairItem?: string[];
  /**
   * @remarks
   * The repair option in the image template.
   * 
   * Valid values:
   * - Standard: standard repair mode.
   * 
   *   The standard repair package for Linux includes the following items:
   *   - GUESTOS.CloudInit
   *   - GUESTOS.Dhcp
   *   - GUESTOS.Virtio
   *   - GUESTOS.OnlineResizeFS
   *   - GUESTOS.Grub
   *   - GUESTOS.Fstab
   *   - GUESTOS.Nvme
   * 
   *   The standard repair package for Windows includes the following items:
   *   - GUESTOS.Virtio
   *   - GUESTOS.Update
   *   - GUESTOS.Hotfix
   *   - GUESTOS.Server
   *   - GUESTOS.Bcd
   *   - GUESTOS.Disk
   *   - GUESTOS.Bootmgr
   *   - GUESTOS.OSLoader
   *   - GUESTOS.Vminit
   * 
   * - All: full repair mode.
   * 
   *   The full repair package for Linux includes all items in the standard repair package, plus the following items:
   * 
   *   - GUESTOS.Selinux
   *   - GUESTOS.SecurityCenterAgent
   * 
   *   The full repair package for Windows includes all items in the standard repair package, plus the following item:
   *   - GUESTOS.Server
   * 
   * 
   * - Customized: custom repair mode. In this mode, the repair items in the repair package are specified by the RepairItem parameter.
   * 
   * > As detection and repair capabilities continue to improve, the included repair items may increase. For more information about the specific meaning of each repair item, see [Overview of image detection](https://help.aliyun.com/document_detail/439819.html).
   * 
   * @example
   * Standard
   */
  repairMode?: string;
  /**
   * @remarks
   * The ID of the enterprise resource group.
   * 
   * @example
   * rg-bp67acfmxazb4p****
   */
  resourceGroupId?: string;
  resourceOwnerAccount?: string;
  resourceOwnerId?: number;
  /**
   * @remarks
   * The system disk size of the intermediate instance. Unit: GiB. Valid values: 20 to 500.
   * 
   * Default value: 40.
   * 
   * @example
   * 40
   */
  systemDiskSize?: number;
  /**
   * @remarks
   * The tags.
   */
  tag?: CreateImagePipelineRequestTag[];
  /**
   * @remarks
   * The content of the image test template. The content size cannot exceed 16 KB. For more information about supported commands, see [Commands supported by Image Builder](https://help.aliyun.com/document_detail/200206.html).
   * 
   * @example
   * COMPONENT ic-bp12dvdzvr9k9*****
   * COMPONENT acs:ecs:cn-hangzhou:18689161186*****:imagecomponent/ComponentName/1.*.*
   */
  testContent?: string;
  /**
   * @remarks
   * The regions to which to distribute the destination image. Valid values of N: 1 to 20.
   * 
   * If you do not specify this parameter, the image is created only in the current region.
   * 
   * @example
   * cn-hangzhou
   */
  toRegionId?: string[];
  /**
   * @remarks
   * The ID of the vSwitch in the VPC.
   * 
   * If you do not specify this parameter, a new VPC and vSwitch are created by default. Make sure that the VPC resource quota in your account is sufficient. For more information, see [Limits](https://help.aliyun.com/document_detail/27750.html).
   * 
   * @example
   * vsw-bp67acfmxazb4p****
   */
  vSwitchId?: string;
  static names(): { [key: string]: string } {
    return {
      addAccount: 'AddAccount',
      advancedOptions: 'AdvancedOptions',
      baseImage: 'BaseImage',
      baseImageType: 'BaseImageType',
      buildContent: 'BuildContent',
      clientToken: 'ClientToken',
      deleteInstanceOnFailure: 'DeleteInstanceOnFailure',
      description: 'Description',
      imageFamily: 'ImageFamily',
      imageName: 'ImageName',
      imageOptions: 'ImageOptions',
      importImageOptions: 'ImportImageOptions',
      instanceType: 'InstanceType',
      internetMaxBandwidthOut: 'InternetMaxBandwidthOut',
      name: 'Name',
      nvmeSupport: 'NvmeSupport',
      ownerAccount: 'OwnerAccount',
      ownerId: 'OwnerId',
      regionId: 'RegionId',
      repairItem: 'RepairItem',
      repairMode: 'RepairMode',
      resourceGroupId: 'ResourceGroupId',
      resourceOwnerAccount: 'ResourceOwnerAccount',
      resourceOwnerId: 'ResourceOwnerId',
      systemDiskSize: 'SystemDiskSize',
      tag: 'Tag',
      testContent: 'TestContent',
      toRegionId: 'ToRegionId',
      vSwitchId: 'VSwitchId',
    };
  }

  static types(): { [key: string]: any } {
    return {
      addAccount: { 'type': 'array', 'itemType': 'number' },
      advancedOptions: CreateImagePipelineRequestAdvancedOptions,
      baseImage: 'string',
      baseImageType: 'string',
      buildContent: 'string',
      clientToken: 'string',
      deleteInstanceOnFailure: 'boolean',
      description: 'string',
      imageFamily: 'string',
      imageName: 'string',
      imageOptions: CreateImagePipelineRequestImageOptions,
      importImageOptions: CreateImagePipelineRequestImportImageOptions,
      instanceType: 'string',
      internetMaxBandwidthOut: 'number',
      name: 'string',
      nvmeSupport: 'string',
      ownerAccount: 'string',
      ownerId: 'number',
      regionId: 'string',
      repairItem: { 'type': 'array', 'itemType': 'string' },
      repairMode: 'string',
      resourceGroupId: 'string',
      resourceOwnerAccount: 'string',
      resourceOwnerId: 'number',
      systemDiskSize: 'number',
      tag: { 'type': 'array', 'itemType': CreateImagePipelineRequestTag },
      testContent: 'string',
      toRegionId: { 'type': 'array', 'itemType': 'string' },
      vSwitchId: 'string',
    };
  }

  validate() {
    if(Array.isArray(this.addAccount)) {
      $dara.Model.validateArray(this.addAccount);
    }
    if(this.advancedOptions && typeof (this.advancedOptions as any).validate === 'function') {
      (this.advancedOptions as any).validate();
    }
    if(this.imageOptions && typeof (this.imageOptions as any).validate === 'function') {
      (this.imageOptions as any).validate();
    }
    if(this.importImageOptions && typeof (this.importImageOptions as any).validate === 'function') {
      (this.importImageOptions as any).validate();
    }
    if(Array.isArray(this.repairItem)) {
      $dara.Model.validateArray(this.repairItem);
    }
    if(Array.isArray(this.tag)) {
      $dara.Model.validateArray(this.tag);
    }
    if(Array.isArray(this.toRegionId)) {
      $dara.Model.validateArray(this.toRegionId);
    }
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

