// This file is auto-generated, don't edit it
import * as $dara from '@darabonba/typescript';


export class ListReviewRulesResponseBodyReviewRules extends $dara.Model {
  /**
   * @remarks
   * The remarks of the audit policy.
   * 
   * @example
   * test
   */
  remark?: string;
  /**
   * @remarks
   * The audit policy ID.
   * 
   * @example
   * 1
   */
  reviewRuleId?: number;
  /**
   * @remarks
   * The audit policy name.
   * 
   * @example
   * rulename
   */
  ruleName?: string;
  /**
   * @remarks
   * The type of auditable asset scope specified in the audit policy. Valid values:
   * 
   * - **1**: All projects.
   * 
   * - **2**: Specified projects.
   * 
   * @example
   * 2
   */
  scopeType?: number;
  static names(): { [key: string]: string } {
    return {
      remark: 'Remark',
      reviewRuleId: 'ReviewRuleId',
      ruleName: 'RuleName',
      scopeType: 'ScopeType',
    };
  }

  static types(): { [key: string]: any } {
    return {
      remark: 'string',
      reviewRuleId: 'number',
      ruleName: 'string',
      scopeType: 'number',
    };
  }

  validate() {
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

export class ListReviewRulesResponseBody extends $dara.Model {
  /**
   * @remarks
   * The value of the MaxResults request parameter if a valid value was specified. Otherwise, the default value is returned.
   * 
   * @example
   * 20
   */
  maxResults?: number;
  /**
   * @remarks
   * The token for the next request. Use this value for the NextToken request parameter in the next paging query. If this field is empty in the response, no more data is available.
   * 
   * @example
   * 4ieSWJCwxvW3dk3wF.BqkrZmP72nWu5zJ5NWydMqyEs****
   */
  nextToken?: string;
  /**
   * @remarks
   * The unique request ID generated by Alibaba Cloud for this request.
   * 
   * @example
   * 50177258-E817-4D2F-A5C6-3FD7BC4806E3
   */
  requestId?: string;
  /**
   * @remarks
   * The list of audit policies.
   */
  reviewRules?: ListReviewRulesResponseBodyReviewRules[];
  /**
   * @remarks
   * The total number of audit policies returned.
   * 
   * @example
   * 5
   */
  totalCount?: number;
  static names(): { [key: string]: string } {
    return {
      maxResults: 'MaxResults',
      nextToken: 'NextToken',
      requestId: 'RequestId',
      reviewRules: 'ReviewRules',
      totalCount: 'TotalCount',
    };
  }

  static types(): { [key: string]: any } {
    return {
      maxResults: 'number',
      nextToken: 'string',
      requestId: 'string',
      reviewRules: { 'type': 'array', 'itemType': ListReviewRulesResponseBodyReviewRules },
      totalCount: 'number',
    };
  }

  validate() {
    if(Array.isArray(this.reviewRules)) {
      $dara.Model.validateArray(this.reviewRules);
    }
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

