// This file is auto-generated, don't edit it
import * as $dara from '@darabonba/typescript';


export class GetMonthlyBillResponseBodyData extends $dara.Model {
  /**
   * @remarks
   * The link to download CSV file, please use HTTP Protocol.
   * 
   * @example
   * intl-reseller-month-bill.oss-ap-southeast-1.aliyuncs.com/statements/month/dts/1064252248461886/202104/Month%20Billing%20Invoice%20202104.pdf?Expires=1671160973&OSSAccessKeyId=TMP.3KhvoD9pW264cPv8sYe8E2zJ5HLWmrijNHgKiKpXcy8yS472BcrvemgTfNrrXKu5fCCdbLr2XhmYAyYPmbCe8zJyEkmYzL&Signature=hns1PgiiYl1WdI%2FdiOqbEdsgmfI%3D
   */
  billLinkCSV?: string;
  /**
   * @remarks
   * The link to download XLSX file, please use HTTP Protocol.
   * 
   * @example
   * intl-reseller-month-bill.oss-ap-southeast-1.aliyuncs.com/statements/month/dts/1064252248461886/202104/Month%20Billing%20Invoice%20202104.pdf?Expires=1671160973&OSSAccessKeyId=TMP.3KhvoD9pW264cPv8sYe8E2zJ5HLWmrijNHgKiKpXcy8yS472BcrvemgTfNrrXKu5fCCdbLr2XhmYAyYPmbCe8zJyEkmYzL&Signature=hns1PgiiYl1WdI%2FdiOqbEdsgmfI%3D
   */
  billLinkXLSX?: string;
  /**
   * @remarks
   * Same as inserted parameter BillOwner.
   * 
   * @example
   * 1
   */
  billOwner?: string;
  /**
   * @remarks
   * Same as inserted parameter BillType.
   * 
   * @example
   * MonthlyInvoice
   */
  billType?: string;
  /**
   * @remarks
   * The URL to download invoice.
   * 
   * @example
   * intl-reseller-month-bill.oss-ap-southeast-1.aliyuncs.com/statements/month/dts/1064252248461886/202104/Month%20Billing%20Invoice%20202104.pdf?Expires=1671160973&OSSAccessKeyId=TMP.3KhvoD9pW264cPv8sYe8E2zJ5HLWmrijNHgKiKpXcy8yS472BcrvemgTfNrrXKu5fCCdbLr2XhmYAyYPmbCe8zJyEkmYzL&Signature=hns1PgiiYl1WdI%2FdiOqbEdsgmfI%3D
   */
  invoiceLink?: string;
  /**
   * @remarks
   * It states the existence of refund invoice. </br>
   * Candidate Values: True/False
   * 
   * @example
   * True
   */
  refundInvoiceFlag?: boolean;
  /**
   * @remarks
   * The URL to download refund invoice.
   * 
   * @example
   * intl-reseller-month-bill.oss-ap-southeast-1.aliyuncs.com/statements/month/dts/1064252248461886/202104/Month%20Billing%20Invoice%20202104.pdf?Expires=1671160973&OSSAccessKeyId=TMP.3KhvoD9pW264cPv8sYe8E2zJ5HLWmrijNHgKiKpXcy8yS472BcrvemgTfNrrXKu5fCCdbLr2XhmYAyYPmbCe8zJyEkmYzL&Signature=hns1PgiiYl1WdI%2FdiOqbEdsgmfI%3D
   */
  refundInvoiceLink?: string;
  /**
   * @remarks
   * Spending Time, refer to the exact time of costuming.
   * 
   * @example
   * 20221201
   */
  spendingTime?: string;
  static names(): { [key: string]: string } {
    return {
      billLinkCSV: 'BillLinkCSV',
      billLinkXLSX: 'BillLinkXLSX',
      billOwner: 'BillOwner',
      billType: 'BillType',
      invoiceLink: 'InvoiceLink',
      refundInvoiceFlag: 'RefundInvoiceFlag',
      refundInvoiceLink: 'RefundInvoiceLink',
      spendingTime: 'SpendingTime',
    };
  }

  static types(): { [key: string]: any } {
    return {
      billLinkCSV: 'string',
      billLinkXLSX: 'string',
      billOwner: 'string',
      billType: 'string',
      invoiceLink: 'string',
      refundInvoiceFlag: 'boolean',
      refundInvoiceLink: 'string',
      spendingTime: 'string',
    };
  }

  validate() {
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

export class GetMonthlyBillResponseBody extends $dara.Model {
  /**
   * @remarks
   * Result Code:
   * * 200 OK
   * * 1109 System error
   * * 3030 Sub Account Nickname exceeds maximum length, maximum length 150 bytes.
   * * 3031 Remark exceeds maximum length, maximum length 3000 bytes.
   * 
   * @example
   * 200
   */
  code?: string;
  /**
   * @remarks
   * The returned data.
   */
  data?: GetMonthlyBillResponseBodyData;
  /**
   * @remarks
   * Same as Code parameters.
   * 
   * @example
   * 200
   */
  message?: string;
  /**
   * @remarks
   * Request ID, the unique request identifier generated by Alibaba Cloud.
   * 
   * @example
   * 210e876f16704666020714468dab35
   */
  requestId?: string;
  /**
   * @remarks
   * Candidate Value: True/False, which indicates whether the current API call itself is successful. It does not guarantee the success of subsequent business operations.
   * 
   * @example
   * true
   */
  success?: boolean;
  static names(): { [key: string]: string } {
    return {
      code: 'Code',
      data: 'Data',
      message: 'Message',
      requestId: 'RequestId',
      success: 'Success',
    };
  }

  static types(): { [key: string]: any } {
    return {
      code: 'string',
      data: GetMonthlyBillResponseBodyData,
      message: 'string',
      requestId: 'string',
      success: 'boolean',
    };
  }

  validate() {
    if(this.data && typeof (this.data as any).validate === 'function') {
      (this.data as any).validate();
    }
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

