// This file is auto-generated, don't edit it
import * as $dara from '@darabonba/typescript';


export class ListImageResponseBodyDataAppList extends $dara.Model {
  /**
   * @remarks
   * The ID of the application.
   * 
   * @example
   * ca-xxx
   */
  appId?: string;
  /**
   * @remarks
   * The name of the application.
   */
  appName?: string;
  static names(): { [key: string]: string } {
    return {
      appId: 'AppId',
      appName: 'AppName',
    };
  }

  static types(): { [key: string]: any } {
    return {
      appId: 'string',
      appName: 'string',
    };
  }

  validate() {
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

export class ListImageResponseBodyDataImageRegionDistributeList extends $dara.Model {
  /**
   * @remarks
   * System image IDs follow a descriptive, human-readable format, while custom image IDs are automatically generated by the system.
   * 
   * @example
   * imgc-xxx
   */
  imageId?: string;
  /**
   * @remarks
   * The progress.
   * 
   * @example
   * 70%
   */
  progress?: string;
  /**
   * @remarks
   * The supported region.
   * 
   * @example
   * cn-shanghai
   */
  regionId?: string;
  /**
   * @remarks
   * The status.
   * 
   * @example
   * INIT
   */
  status?: string;
  /**
   * @remarks
   * The version of the image.
   * 
   * @example
   * iv-xxx
   */
  versionId?: string;
  static names(): { [key: string]: string } {
    return {
      imageId: 'ImageId',
      progress: 'Progress',
      regionId: 'RegionId',
      status: 'Status',
      versionId: 'VersionId',
    };
  }

  static types(): { [key: string]: any } {
    return {
      imageId: 'string',
      progress: 'string',
      regionId: 'string',
      status: 'string',
      versionId: 'string',
    };
  }

  validate() {
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

export class ListImageResponseBodyData extends $dara.Model {
  /**
   * @remarks
   * The tenant ID.
   * 
   * @example
   * 123456789
   */
  aliUid?: number;
  /**
   * @remarks
   * The application configuration.
   */
  appList?: ListImageResponseBodyDataAppList[];
  /**
   * @remarks
   * The base image ID.
   * 
   * @example
   * imgc-xxx
   */
  baseImageId?: string;
  /**
   * @remarks
   * The version of the base image.
   * 
   * @example
   * iv-xxx
   */
  baseImageVersion?: string;
  /**
   * @remarks
   * The service type.
   * 
   * @example
   * 1
   */
  bizType?: number;
  /**
   * @remarks
   * Specifies whether to use the compatibility mode.
   * 
   * @example
   * true
   */
  compatibleMode?: boolean;
  /**
   * @remarks
   * The size of the data disk. Unit: GiB.
   * 
   * @example
   * 100
   */
  dataDiskSize?: number;
  /**
   * @remarks
   * The description of the image.
   */
  description?: string;
  /**
   * @remarks
   * The name of the release.
   */
  distro?: string;
  /**
   * @remarks
   * The information about each driver.
   */
  driverList?: string[];
  /**
   * @remarks
   * The image feature tags.
   */
  featureList?: string[];
  /**
   * @remarks
   * >  This parameter is not available for public use.
   */
  fotaChannel?: string;
  /**
   * @remarks
   * The FOTA version.
   * 
   * @example
   * 2.3.0-xxx
   */
  fotaVersion?: string;
  /**
   * @remarks
   * The creation time.
   * 
   * @example
   * 2025-04-25 15:13:57
   */
  gmtCreate?: string;
  /**
   * @remarks
   * The update time.
   * 
   * @example
   * 2025-04-25 15:13:57
   */
  gmtModified?: string;
  /**
   * @remarks
   * The image creation type.
   * 
   * Valid values:
   * 
   * *   BY_SNAPSHOT_ID: The image is created from the snapshot or contains only a system disk.
   * *   BUILDER_MANUAL: The image is manually generated.
   * *   INSTANCE_AUTO: The image is automatically generated based on an instance.
   * *   BY_INSTANCE_ID: The image is created from an instance or contains both a system disk and data disks.
   * 
   * @example
   * BUILDER_MANUAL
   */
  imageCreateMode?: string;
  /**
   * @remarks
   * System image IDs follow a descriptive, human-readable format, while custom image IDs are automatically generated by the system.
   * 
   * @example
   * imgc-xxxx
   */
  imageId?: string;
  /**
   * @remarks
   * The image name.
   * 
   * @example
   * DemoImage
   */
  imageName?: string;
  /**
   * @remarks
   * Layered supported regions information.
   */
  imageRegionDistributeList?: ListImageResponseBodyDataImageRegionDistributeList[];
  /**
   * @remarks
   * The region ID.
   */
  imageRegionList?: string[];
  /**
   * @remarks
   * The type of the image.
   * 
   * @example
   * User
   */
  imageType?: string;
  /**
   * @remarks
   * The image language. When the packaging type is VHD or Container, the image inherits its properties from the ECS-type image within the same image bundle.
   * 
   * @example
   * zh-CN
   */
  language?: string;
  /**
   * @remarks
   * The latest sub-version of the image. (An image consists of multiple sub-versions.)
   * 
   * @example
   * iv-xxx
   */
  latestVersionId?: string;
  /**
   * @remarks
   * Indicates whether the current version is the active version.
   */
  onlineVersion?: boolean;
  /**
   * @remarks
   * This image tag currently points to the specified sub-version of the parent image. (An image consists of multiple sub-versions.)
   * 
   * @example
   * iv-xxxx
   */
  onlineVersionId?: string;
  /**
   * @remarks
   * The type of the image.
   * 
   * @example
   * Windows
   */
  osType?: string;
  /**
   * @remarks
   * The image encapsulation type.
   * 
   * @example
   * ECS
   */
  packageType?: string;
  /**
   * @remarks
   * The ID of the parent image from which this image is derived. Note: This field is only applicable to custom images, as system images do not have a parent.
   * 
   * @example
   * imgc-xxx
   */
  parentImageId?: string;
  /**
   * @remarks
   * The version of the parent image.
   * 
   * @example
   * iv-xxx
   */
  parentImageVersion?: string;
  /**
   * @remarks
   * The operating system platform of the image.
   * 
   * >  When the packaging type is VHD or Container, the image inherits its properties from the ECS-type image within the same image bundle.
   * 
   * @example
   * Windows
   */
  platform?: number;
  /**
   * @remarks
   * The name of the operating system platform.
   * 
   * @example
   * Windows Server 2022
   */
  platformName?: string;
  /**
   * @remarks
   * The product type.
   * 
   * @example
   * CloudApp
   */
  productType?: string;
  /**
   * @remarks
   * The protocol type.
   * 
   * @example
   * ASP
   */
  protocolType?: string;
  /**
   * @remarks
   * The types of resources that are supported by the images.
   * 
   * @example
   * ["eds.cpu.category"]
   */
  resourceInstanceCategory?: string;
  /**
   * @remarks
   * The type of the session.
   * 
   * Valid values:
   * 
   * *   SINGLE_SESSION
   * *   MULTIPLE_SESSION
   * 
   * @example
   * SINGLE_SESSION
   */
  sessionType?: string;
  /**
   * @remarks
   * The state of the image.
   * 
   * @example
   * INIT
   */
  status?: string;
  /**
   * @remarks
   * The supported languages.
   */
  supportedLanguageList?: string[];
  /**
   * @remarks
   * The size of the system disk. Unit: GiB.
   * 
   * >  The system disk must be at least as large as the image.
   * 
   * @example
   * 40
   */
  systemDiskSize?: number;
  /**
   * @remarks
   * The version of the image.
   * 
   * @example
   * iv-xxx
   */
  versionId?: string;
  /**
   * @remarks
   * The version number.
   * 
   * @example
   * v0.1.0
   */
  versionName?: string;
  /**
   * @remarks
   * Specifies whether to enable disk encryption.
   * 
   * @example
   * true
   */
  volumeEncryptionEnabled?: boolean;
  /**
   * @remarks
   * The ID of the Key Management Service (KMS) key that is used to encrypt the disk.
   * 
   * @example
   * a7b3c0c8-xxxx
   */
  volumeEncryptionKey?: string;
  static names(): { [key: string]: string } {
    return {
      aliUid: 'AliUid',
      appList: 'AppList',
      baseImageId: 'BaseImageId',
      baseImageVersion: 'BaseImageVersion',
      bizType: 'BizType',
      compatibleMode: 'CompatibleMode',
      dataDiskSize: 'DataDiskSize',
      description: 'Description',
      distro: 'Distro',
      driverList: 'DriverList',
      featureList: 'FeatureList',
      fotaChannel: 'FotaChannel',
      fotaVersion: 'FotaVersion',
      gmtCreate: 'GmtCreate',
      gmtModified: 'GmtModified',
      imageCreateMode: 'ImageCreateMode',
      imageId: 'ImageId',
      imageName: 'ImageName',
      imageRegionDistributeList: 'ImageRegionDistributeList',
      imageRegionList: 'ImageRegionList',
      imageType: 'ImageType',
      language: 'Language',
      latestVersionId: 'LatestVersionId',
      onlineVersion: 'OnlineVersion',
      onlineVersionId: 'OnlineVersionId',
      osType: 'OsType',
      packageType: 'PackageType',
      parentImageId: 'ParentImageId',
      parentImageVersion: 'ParentImageVersion',
      platform: 'Platform',
      platformName: 'PlatformName',
      productType: 'ProductType',
      protocolType: 'ProtocolType',
      resourceInstanceCategory: 'ResourceInstanceCategory',
      sessionType: 'SessionType',
      status: 'Status',
      supportedLanguageList: 'SupportedLanguageList',
      systemDiskSize: 'SystemDiskSize',
      versionId: 'VersionId',
      versionName: 'VersionName',
      volumeEncryptionEnabled: 'VolumeEncryptionEnabled',
      volumeEncryptionKey: 'VolumeEncryptionKey',
    };
  }

  static types(): { [key: string]: any } {
    return {
      aliUid: 'number',
      appList: { 'type': 'array', 'itemType': ListImageResponseBodyDataAppList },
      baseImageId: 'string',
      baseImageVersion: 'string',
      bizType: 'number',
      compatibleMode: 'boolean',
      dataDiskSize: 'number',
      description: 'string',
      distro: 'string',
      driverList: { 'type': 'array', 'itemType': 'string' },
      featureList: { 'type': 'array', 'itemType': 'string' },
      fotaChannel: 'string',
      fotaVersion: 'string',
      gmtCreate: 'string',
      gmtModified: 'string',
      imageCreateMode: 'string',
      imageId: 'string',
      imageName: 'string',
      imageRegionDistributeList: { 'type': 'array', 'itemType': ListImageResponseBodyDataImageRegionDistributeList },
      imageRegionList: { 'type': 'array', 'itemType': 'string' },
      imageType: 'string',
      language: 'string',
      latestVersionId: 'string',
      onlineVersion: 'boolean',
      onlineVersionId: 'string',
      osType: 'string',
      packageType: 'string',
      parentImageId: 'string',
      parentImageVersion: 'string',
      platform: 'number',
      platformName: 'string',
      productType: 'string',
      protocolType: 'string',
      resourceInstanceCategory: 'string',
      sessionType: 'string',
      status: 'string',
      supportedLanguageList: { 'type': 'array', 'itemType': 'string' },
      systemDiskSize: 'number',
      versionId: 'string',
      versionName: 'string',
      volumeEncryptionEnabled: 'boolean',
      volumeEncryptionKey: 'string',
    };
  }

  validate() {
    if(Array.isArray(this.appList)) {
      $dara.Model.validateArray(this.appList);
    }
    if(Array.isArray(this.driverList)) {
      $dara.Model.validateArray(this.driverList);
    }
    if(Array.isArray(this.featureList)) {
      $dara.Model.validateArray(this.featureList);
    }
    if(Array.isArray(this.imageRegionDistributeList)) {
      $dara.Model.validateArray(this.imageRegionDistributeList);
    }
    if(Array.isArray(this.imageRegionList)) {
      $dara.Model.validateArray(this.imageRegionList);
    }
    if(Array.isArray(this.supportedLanguageList)) {
      $dara.Model.validateArray(this.supportedLanguageList);
    }
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

export class ListImageResponseBody extends $dara.Model {
  /**
   * @remarks
   * The HTTP status code that is returned.
   * 
   * @example
   * 200
   */
  code?: string;
  /**
   * @remarks
   * The total number of entries.
   * 
   * @example
   * 22
   */
  count?: number;
  /**
   * @remarks
   * The returned data.
   */
  data?: ListImageResponseBodyData[];
  /**
   * @remarks
   * The message that is returned for the request.
   * 
   * @example
   * success
   */
  message?: string;
  /**
   * @remarks
   * The page number returned.
   * 
   * @example
   * 1
   */
  pageNumber?: number;
  /**
   * @remarks
   * The number of entries per page.
   * 
   * @example
   * 10
   */
  pageSize?: number;
  /**
   * @remarks
   * The request ID.
   * 
   * @example
   * 8737D130-BFD0-5D51-96F6-C08EB1139A25
   */
  requestId?: string;
  /**
   * @remarks
   * Indicates whether the request was successful.
   * 
   * Valid values:
   * 
   * *   true: The request is successful.
   * *   false: The request failed.
   * 
   * @example
   * true
   */
  success?: boolean;
  static names(): { [key: string]: string } {
    return {
      code: 'Code',
      count: 'Count',
      data: 'Data',
      message: 'Message',
      pageNumber: 'PageNumber',
      pageSize: 'PageSize',
      requestId: 'RequestId',
      success: 'Success',
    };
  }

  static types(): { [key: string]: any } {
    return {
      code: 'string',
      count: 'number',
      data: { 'type': 'array', 'itemType': ListImageResponseBodyData },
      message: 'string',
      pageNumber: 'number',
      pageSize: 'number',
      requestId: 'string',
      success: 'boolean',
    };
  }

  validate() {
    if(Array.isArray(this.data)) {
      $dara.Model.validateArray(this.data);
    }
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

