// This file is auto-generated, don't edit it
import * as $dara from '@darabonba/typescript';
import { InputCodeLocation } from "./InputCodeLocation";
import { CustomContainerConfig } from "./CustomContainerConfig";
import { CustomDNS } from "./CustomDns";
import { CustomRuntimeConfig } from "./CustomRuntimeConfig";
import { GPUConfig } from "./Gpuconfig";
import { InstanceLifecycleConfig } from "./InstanceLifecycleConfig";
import { JuiceFsConfig } from "./JuiceFsConfig";
import { LogConfig } from "./LogConfig";
import { MicroSandboxConfig } from "./MicroSandboxConfig";
import { NASConfig } from "./Nasconfig";
import { OSSMountConfig } from "./OssmountConfig";
import { PolarFsConfig } from "./PolarFsConfig";
import { TracingConfig } from "./TracingConfig";
import { VPCConfig } from "./Vpcconfig";


export class UpdateFunctionInput extends $dara.Model {
  /**
   * @remarks
   * The ZIP package of the function code. Specify either code or customContainerConfig.
   */
  code?: InputCodeLocation;
  /**
   * @remarks
   * The CPU specification of the function. Unit: vCPU. The value must be a multiple of 0.05 vCPU.
   * 
   * @example
   * 1
   */
  cpu?: number;
  /**
   * @remarks
   * The configuration of the custom container runtime. After this parameter is configured, the function can use a custom container image for execution. Specify either code or customContainerConfig.
   */
  customContainerConfig?: CustomContainerConfig;
  /**
   * @remarks
   * The custom DNS configuration.
   */
  customDNS?: CustomDNS;
  /**
   * @remarks
   * The custom runtime configuration.
   */
  customRuntimeConfig?: CustomRuntimeConfig;
  /**
   * @remarks
   * The description of the function.
   * 
   * @example
   * my function
   */
  description?: string;
  /**
   * @remarks
   * Specifies whether to disable STS token injection. Valid values:
   * - None: STS tokens are injected in all methods.
   * - Env: STS tokens are not injected through environment variables.
   * - Request: STS tokens are not injected through requests, including context and headers.
   * - All: STS tokens are not injected in any method.
   * 
   * @example
   * Env
   */
  disableInjectCredentials?: string;
  /**
   * @remarks
   * Specifies whether to disable the creation of on-demand instances. If this feature is enabled, on-demand instances are not created, and only provisioned instances can be used.
   * 
   * @deprecated
   */
  disableOndemand?: boolean;
  /**
   * @remarks
   * The disk specification of the function. Unit: MB. Valid values: 512 and 10240.
   * 
   * @example
   * 512
   */
  diskSize?: number;
  /**
   * @remarks
   * Specifies whether to allow provisioned instances of GPU functions to be long-running. When this feature is enabled, function instances that are created are not injected with STS tokens.
   * 
   * @deprecated
   */
  enableLongLiving?: boolean;
  /**
   * @remarks
   * The environment variables of the function. You can access the configured environment variables in the runtime environment.
   */
  environmentVariables?: { [key: string]: string };
  /**
   * @remarks
   * The GPU configuration of the function.
   */
  gpuConfig?: GPUConfig;
  /**
   * @remarks
   * The function entry point. The specific format depends on the runtime.
   * 
   * @example
   * index.handler
   */
  handler?: string;
  /**
   * @remarks
   * The deferred release time of the instance.
   * 
   * @example
   * 100
   */
  idleTimeout?: number;
  /**
   * @remarks
   * The maximum concurrency of an instance.
   * 
   * @example
   * 1
   */
  instanceConcurrency?: number;
  /**
   * @remarks
   * The instance isolation mode.
   */
  instanceIsolationMode?: string;
  /**
   * @remarks
   * The instance lifecycle hook configuration.
   */
  instanceLifecycleConfig?: InstanceLifecycleConfig;
  /**
   * @remarks
   * Specifies whether to allow access to the Internet.
   * 
   * @example
   * true
   */
  internetAccess?: boolean;
  juiceFsConfig?: JuiceFsConfig;
  /**
   * @remarks
   * The list of layers. Multiple layers are merged in descending order of array index. Files in a layer with a smaller index overwrite files with the same name in a layer with a larger index.
   */
  layers?: string[];
  /**
   * @remarks
   * The log configuration. Logs generated by the function are written to the configured Logstore.
   */
  logConfig?: LogConfig;
  /**
   * @remarks
   * The memory specification of the function. Unit: MB. The value must be a multiple of 64 MB. The memory specification varies based on the function instance type.
   * 
   * @example
   * 512
   */
  memorySize?: number;
  microSandboxConfig?: MicroSandboxConfig;
  /**
   * @remarks
   * The NAS configuration. After this parameter is configured, the function can access the specified NAS resources.
   */
  nasConfig?: NASConfig;
  /**
   * @remarks
   * The OSS mount configuration.
   */
  ossMountConfig?: OSSMountConfig;
  /**
   * @remarks
   * The PolarFs configuration. After this parameter is configured, the function can access the specified PolarFs resources.
   */
  polarFsConfig?: PolarFsConfig;
  /**
   * @remarks
   * The Alibaba Cloud Resource Access Management (RAM) role that grants Function Compute the required permissions. Scenarios include: 1. Sending logs generated by the function to your Logstore. 2. Generating temporary access tokens for the function to access other cloud resources during the execute procedure.
   * 
   * @example
   * acs:ram::188077086902****:role/fc-test
   */
  role?: string;
  /**
   * @remarks
   * The runtime environment of the function.
   * 
   * @example
   * nodejs14
   */
  runtime?: string;
  /**
   * @remarks
   * The affinity policy for Function Compute invocation requests. To implement request affinity for the MCP SSE protocol, set this parameter to MCP_SSE. To use cookie-based affinity, set this parameter to GENERATED_COOKIE. To use header-based affinity, set this parameter to HEADER_FIELD. If this parameter is not set or is set to NONE, no affinity is applied, and requests are routed based on the default scheduling policy of Function Compute.
   * 
   * @example
   * MCP_SSE
   */
  sessionAffinity?: string;
  /**
   * @remarks
   * The affinity configuration that corresponds to the sessionAffinity type. For MCP_SSE affinity, configure MCPSSESessionAffinityConfig. For cookie-based affinity, configure CookieSessionAffinityConfig. For header field affinity, configure HeaderFieldSessionAffinityConfig.
   * 
   * @example
   * {\\"sseEndpointPath\\":\\"/sse\\", \\"sessionConcurrencyPerInstance\\":20}
   */
  sessionAffinityConfig?: string;
  /**
   * @remarks
   * The timeout period for function execution. Unit: seconds. Minimum value: 1. Default value: 3. The function is terminated if it exceeds this time limit.
   * 
   * @example
   * 60
   */
  timeout?: number;
  /**
   * @remarks
   * The Tracing Analysis configuration. After Function Compute is integrated with Tracing Analysis, you can record the time consumed by requests in Function Compute, view the cold start time of functions, and record the time consumed by internal function operations.
   */
  tracingConfig?: TracingConfig;
  /**
   * @remarks
   * The VPC configuration. After this parameter is configured, the function can access the specified VPC resources.
   */
  vpcConfig?: VPCConfig;
  static names(): { [key: string]: string } {
    return {
      code: 'code',
      cpu: 'cpu',
      customContainerConfig: 'customContainerConfig',
      customDNS: 'customDNS',
      customRuntimeConfig: 'customRuntimeConfig',
      description: 'description',
      disableInjectCredentials: 'disableInjectCredentials',
      disableOndemand: 'disableOndemand',
      diskSize: 'diskSize',
      enableLongLiving: 'enableLongLiving',
      environmentVariables: 'environmentVariables',
      gpuConfig: 'gpuConfig',
      handler: 'handler',
      idleTimeout: 'idleTimeout',
      instanceConcurrency: 'instanceConcurrency',
      instanceIsolationMode: 'instanceIsolationMode',
      instanceLifecycleConfig: 'instanceLifecycleConfig',
      internetAccess: 'internetAccess',
      juiceFsConfig: 'juiceFsConfig',
      layers: 'layers',
      logConfig: 'logConfig',
      memorySize: 'memorySize',
      microSandboxConfig: 'microSandboxConfig',
      nasConfig: 'nasConfig',
      ossMountConfig: 'ossMountConfig',
      polarFsConfig: 'polarFsConfig',
      role: 'role',
      runtime: 'runtime',
      sessionAffinity: 'sessionAffinity',
      sessionAffinityConfig: 'sessionAffinityConfig',
      timeout: 'timeout',
      tracingConfig: 'tracingConfig',
      vpcConfig: 'vpcConfig',
    };
  }

  static types(): { [key: string]: any } {
    return {
      code: InputCodeLocation,
      cpu: 'number',
      customContainerConfig: CustomContainerConfig,
      customDNS: CustomDNS,
      customRuntimeConfig: CustomRuntimeConfig,
      description: 'string',
      disableInjectCredentials: 'string',
      disableOndemand: 'boolean',
      diskSize: 'number',
      enableLongLiving: 'boolean',
      environmentVariables: { 'type': 'map', 'keyType': 'string', 'valueType': 'string' },
      gpuConfig: GPUConfig,
      handler: 'string',
      idleTimeout: 'number',
      instanceConcurrency: 'number',
      instanceIsolationMode: 'string',
      instanceLifecycleConfig: InstanceLifecycleConfig,
      internetAccess: 'boolean',
      juiceFsConfig: JuiceFsConfig,
      layers: { 'type': 'array', 'itemType': 'string' },
      logConfig: LogConfig,
      memorySize: 'number',
      microSandboxConfig: MicroSandboxConfig,
      nasConfig: NASConfig,
      ossMountConfig: OSSMountConfig,
      polarFsConfig: PolarFsConfig,
      role: 'string',
      runtime: 'string',
      sessionAffinity: 'string',
      sessionAffinityConfig: 'string',
      timeout: 'number',
      tracingConfig: TracingConfig,
      vpcConfig: VPCConfig,
    };
  }

  validate() {
    if(this.code && typeof (this.code as any).validate === 'function') {
      (this.code as any).validate();
    }
    if(this.customContainerConfig && typeof (this.customContainerConfig as any).validate === 'function') {
      (this.customContainerConfig as any).validate();
    }
    if(this.customDNS && typeof (this.customDNS as any).validate === 'function') {
      (this.customDNS as any).validate();
    }
    if(this.customRuntimeConfig && typeof (this.customRuntimeConfig as any).validate === 'function') {
      (this.customRuntimeConfig as any).validate();
    }
    if(this.environmentVariables) {
      $dara.Model.validateMap(this.environmentVariables);
    }
    if(this.gpuConfig && typeof (this.gpuConfig as any).validate === 'function') {
      (this.gpuConfig as any).validate();
    }
    if(this.instanceLifecycleConfig && typeof (this.instanceLifecycleConfig as any).validate === 'function') {
      (this.instanceLifecycleConfig as any).validate();
    }
    if(this.juiceFsConfig && typeof (this.juiceFsConfig as any).validate === 'function') {
      (this.juiceFsConfig as any).validate();
    }
    if(Array.isArray(this.layers)) {
      $dara.Model.validateArray(this.layers);
    }
    if(this.logConfig && typeof (this.logConfig as any).validate === 'function') {
      (this.logConfig as any).validate();
    }
    if(this.microSandboxConfig && typeof (this.microSandboxConfig as any).validate === 'function') {
      (this.microSandboxConfig as any).validate();
    }
    if(this.nasConfig && typeof (this.nasConfig as any).validate === 'function') {
      (this.nasConfig as any).validate();
    }
    if(this.ossMountConfig && typeof (this.ossMountConfig as any).validate === 'function') {
      (this.ossMountConfig as any).validate();
    }
    if(this.polarFsConfig && typeof (this.polarFsConfig as any).validate === 'function') {
      (this.polarFsConfig as any).validate();
    }
    if(this.tracingConfig && typeof (this.tracingConfig as any).validate === 'function') {
      (this.tracingConfig as any).validate();
    }
    if(this.vpcConfig && typeof (this.vpcConfig as any).validate === 'function') {
      (this.vpcConfig as any).validate();
    }
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

