// This file is auto-generated, don't edit it
import * as $dara from '@darabonba/typescript';


export class EnableHBaseueModuleRequest extends $dara.Model {
  /**
   * @remarks
   * The auto-renewal period of the instance. Unit: months.
   * 
   * > <ul><li>The default value of the auto-renewal period is 0, which indicates that the instance is not automatically renewed after the instance expires.</li>
   * <li>For example, if the auto-renewal period is set to 2, the instance is automatically renewed for two months after the instance expires.</li></ul>
   * 
   * @example
   * 2
   */
  autoRenewPeriod?: number;
  /**
   * @remarks
   * The ID of the BDS cluster associated with the ApsaraDB for HBase Performance-enhanced Edition instance.
   * 
   * @example
   * bds-bp174pm3tsk3****
   */
  bdsId?: string;
  /**
   * @remarks
   * The client token that is used to ensure the idempotence of the request. The value of this parameter is generated by the client. The value must be unique among different requests, is case-sensitive, and cannot exceed 64 ASCII characters in length.
   * 
   * @example
   * ETnLKlblzczshOTUbOCz****
   */
  clientToken?: string;
  /**
   * @remarks
   * The node specifications of the core node. You can invoke the [DescribeAvailableResource](https://help.aliyun.com/document_detail/188244.html) operation to obtain the specification value.
   * 
   * This parameter is required.
   * 
   * @example
   * hbase.sn1.large
   */
  coreInstanceType?: string;
  /**
   * @remarks
   * The disk size per node. Unit: GB.
   * 
   * - If the instance is a single-node instance, the disk size of a single core node ranges from 20 to 500 GB, with a step size of 1 GB.
   * - If the instance uses cloud disks, the disk size of a single core node ranges from 400 to 64,000 GB, with a step size of 40 GB.
   * 
   * @example
   * 400
   */
  diskSize?: number;
  /**
   * @remarks
   * The disk type of the core node. Valid values:
   * 
   * - cloud_efficiency: ultra cloud disk.
   * - cloud_ssd: standard SSD.
   * - local_hdd_pro: local HDD.
   * - local_ssd_pro: local SSD.
   * - cloud_essd_pl1: ESSD.
   * 
   * @example
   * cloud_ssd
   */
  diskType?: string;
  /**
   * @remarks
   * The instance ID of the ApsaraDB for HBase Performance-enhanced Edition database.
   * 
   * This parameter is required.
   * 
   * @example
   * ld-bp150tns0sjxs****
   */
  hbaseueClusterId?: string;
  /**
   * @remarks
   * The node specifications of the master node. You can invoke the [DescribeAvailableResource](https://help.aliyun.com/document_detail/188244.html) operation to obtain the specification value.
   * 
   * @example
   * hbase.sn1.large
   */
  masterInstanceType?: string;
  /**
   * @remarks
   * The name of the extension cluster.
   * 
   * @example
   * cluster-name
   */
  moduleClusterName?: string;
  /**
   * @remarks
   * The type of the extension module. Set the value to solr.
   * 
   * This parameter is required.
   * 
   * @example
   * solr
   */
  moduleTypeName?: string;
  /**
   * @remarks
   * The number of nodes. Valid values:
   * 
   * - If the instance is a single-node instance, the number of core nodes is fixed to 1.
   * - If the instance uses cloud disks, the number of core nodes ranges from 2 to 100.
   * 
   * This parameter is required.
   * 
   * @example
   * 2
   */
  nodeCount?: number;
  /**
   * @remarks
   * The billing method of the instance. Valid values:
   * 
   * - Prepaid: subscription.
   * - Postpaid: pay-as-you-go.
   * 
   * This parameter is required.
   * 
   * @example
   * Prepaid
   */
  payType?: string;
  /**
   * @remarks
   * The subscription duration of the subscription instance. Valid values:
   * 
   * - If PeriodUnit is set to year, the valid values are 1 to 3.
   * - If PeriodUnit is set to month, the valid values are 1 to 9.
   * 
   * > This parameter is required only when the billing method is Prepaid.
   * 
   * @example
   * 6
   */
  period?: number;
  /**
   * @remarks
   * The unit of the subscription duration for the subscription instance. Valid values:
   * 
   * - **year**
   * - **month**
   * 
   * >  This parameter is required only when the billing method is **Prepaid**.
   * 
   * @example
   * month
   */
  periodUnit?: string;
  /**
   * @remarks
   * The ID of the region in which the instance resides. You can call the [DescribeRegions](https://help.aliyun.com/document_detail/144489.html) operation to obtain the region ID.
   * 
   * This parameter is required.
   * 
   * @example
   * cn-shenzhen
   */
  regionId?: string;
  /**
   * @remarks
   * The ID of the virtual private cloud (VPC).
   * 
   * This parameter is required.
   * 
   * @example
   * vpc-bp120k6ixs4eog*****
   */
  vpcId?: string;
  /**
   * @remarks
   * The ID of the vSwitch in the VPC.
   * 
   * This parameter is required.
   * 
   * @example
   * vsw-bp191ipotqj1ssyl*****
   */
  vswitchId?: string;
  /**
   * @remarks
   * The ID of the zone. You can call the [DescribeRegions](https://help.aliyun.com/document_detail/144489.html) operation to obtain the zone ID.
   * 
   * This parameter is required.
   * 
   * @example
   * cn-shenzhen-e
   */
  zoneId?: string;
  static names(): { [key: string]: string } {
    return {
      autoRenewPeriod: 'AutoRenewPeriod',
      bdsId: 'BdsId',
      clientToken: 'ClientToken',
      coreInstanceType: 'CoreInstanceType',
      diskSize: 'DiskSize',
      diskType: 'DiskType',
      hbaseueClusterId: 'HbaseueClusterId',
      masterInstanceType: 'MasterInstanceType',
      moduleClusterName: 'ModuleClusterName',
      moduleTypeName: 'ModuleTypeName',
      nodeCount: 'NodeCount',
      payType: 'PayType',
      period: 'Period',
      periodUnit: 'PeriodUnit',
      regionId: 'RegionId',
      vpcId: 'VpcId',
      vswitchId: 'VswitchId',
      zoneId: 'ZoneId',
    };
  }

  static types(): { [key: string]: any } {
    return {
      autoRenewPeriod: 'number',
      bdsId: 'string',
      clientToken: 'string',
      coreInstanceType: 'string',
      diskSize: 'number',
      diskType: 'string',
      hbaseueClusterId: 'string',
      masterInstanceType: 'string',
      moduleClusterName: 'string',
      moduleTypeName: 'string',
      nodeCount: 'number',
      payType: 'string',
      period: 'number',
      periodUnit: 'string',
      regionId: 'string',
      vpcId: 'string',
      vswitchId: 'string',
      zoneId: 'string',
    };
  }

  validate() {
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

