// This file is auto-generated, don't edit it
import * as $dara from '@darabonba/typescript';


export class ListTransitRouterRouteEntriesResponseBodyTransitRouterRouteEntriesPathAttributes extends $dara.Model {
  /**
   * @remarks
   * The list of AS Path attributes of the route entry.
   */
  asPaths?: string[];
  /**
   * @remarks
   * The list of Community attributes of the route entry.
   */
  communities?: string[];
  /**
   * @remarks
   * The instance ID of the original instance from which the route entry originates.
   * 
   * @example
   * vbr-m5ent6du8deaq5*****
   */
  originInstanceId?: string;
  /**
   * @remarks
   * The type of the instance from which the route originates.
   * 
   * - **VPC**: Virtual Private Cloud (VPC) instance.
   * - **VBR**: Virtual Border Router (VBR) instance.
   * - **TR**: transit router instance.
   * - **VPN**: IPsec connection instance.
   * - **CCN**: Cloud Connect Network (CCN) instance.
   * 
   * @example
   * VBR
   */
  originInstanceType?: string;
  /**
   * @remarks
   * The original route type when the route was generated.
   * 
   * - **System**: system route.
   * - **Custom**: custom route.
   * - **Static**: static route.
   * - **BGP**: BGP route.
   * - **BlackHole**: blackhole route.
   * 
   * @example
   * BGP
   */
  originRouteType?: string;
  /**
   * @remarks
   * The priority of the route entry.
   * 
   * A smaller value indicates a higher priority.
   * 
   * @example
   * 50
   */
  preference?: number;
  static names(): { [key: string]: string } {
    return {
      asPaths: 'AsPaths',
      communities: 'Communities',
      originInstanceId: 'OriginInstanceId',
      originInstanceType: 'OriginInstanceType',
      originRouteType: 'OriginRouteType',
      preference: 'Preference',
    };
  }

  static types(): { [key: string]: any } {
    return {
      asPaths: { 'type': 'array', 'itemType': 'string' },
      communities: { 'type': 'array', 'itemType': 'string' },
      originInstanceId: 'string',
      originInstanceType: 'string',
      originRouteType: 'string',
      preference: 'number',
    };
  }

  validate() {
    if(Array.isArray(this.asPaths)) {
      $dara.Model.validateArray(this.asPaths);
    }
    if(Array.isArray(this.communities)) {
      $dara.Model.validateArray(this.communities);
    }
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

export class ListTransitRouterRouteEntriesResponseBodyTransitRouterRouteEntries extends $dara.Model {
  /**
   * @remarks
   * The time when the route entry was created.
   * 
   * The time is displayed in UTC in the YYYY-MM-DDThh:mmZ format.
   * 
   * > This parameter is returned only for statically configured routes.
   * 
   * @example
   * 2021-06-15T07:01Z
   */
  createTime?: string;
  /**
   * @remarks
   * Indicates whether the current route entry can be modified.
   * 
   * - **true**: the route entry can be modified. You can delete the route entry.
   * - **false**: the route entry cannot be modified. The route entry is automatically generated by the system and does not support editing.
   * 
   * @example
   * false
   */
  operationalMode?: boolean;
  /**
   * @remarks
   * The path attributes of the route.
   */
  pathAttributes?: ListTransitRouterRouteEntriesResponseBodyTransitRouterRouteEntriesPathAttributes;
  /**
   * @remarks
   * The ID of the prefix list.
   * 
   * @example
   * pl-k1ainl66z3527773d****
   */
  prefixListId?: string;
  /**
   * @remarks
   * The tag of the route entry.
   * 
   * The only valid value is **PermitVbr**, which indicates that the current route entry is propagated only to the route tables of VBR instances under the transit router instance.
   * 
   * > This parameter is returned only for system-generated routes for transit router CIDR blocks.
   * 
   * @example
   * PermitVbr
   */
  tag?: string;
  /**
   * @remarks
   * The description of the route entry.
   * 
   * > This parameter is returned only for statically configured routes.
   * 
   * @example
   * CidrRoute
   */
  transitRouterRouteEntryDescription?: string;
  /**
   * @remarks
   * The destination CIDR block of the route entry. An IPv4 CIDR block or an IPv6 CIDR block is returned.
   * 
   * @example
   * 192.168.0.0/24
   */
  transitRouterRouteEntryDestinationCidrBlock?: string;
  /**
   * @remarks
   * The ID of the route entry.
   * 
   * > This parameter is returned only for statically configured routes.
   * 
   * @example
   * rte-oklkgwmj97z6dn****
   */
  transitRouterRouteEntryId?: string;
  /**
   * @remarks
   * The name of the route entry.
   * 
   * > This parameter is returned only for statically configured routes.
   * 
   * @example
   * testname
   */
  transitRouterRouteEntryName?: string;
  /**
   * @remarks
   * The next hop ID of the route entry. This parameter is not returned for blackhole routes.
   * 
   * @example
   * tr-attach-vx6iwhjr1x1j78****
   */
  transitRouterRouteEntryNextHopId?: string;
  /**
   * @remarks
   * The instance ID of the next hop of the route entry.
   * 
   * @example
   * vpc-m5ent6du8deaq5*****
   */
  transitRouterRouteEntryNextHopResourceId?: string;
  /**
   * @remarks
   * The type of the next hop instance of the route entry.
   * 
   * - **VPC**: Virtual Private Cloud (VPC) instance.
   * - **VBR**: Virtual Border Router (VBR) instance.
   * - **TR**: transit router instance.
   * - **VPN**: IPsec connection instance.
   * 
   * @example
   * VPC
   */
  transitRouterRouteEntryNextHopResourceType?: string;
  /**
   * @remarks
   * The next hop type of the route entry.
   * 
   * - **BlackHole**: the route entry is a blackhole route. All traffic destined for the destination CIDR block is dropped.
   * - **Attachment**: the next hop of the route entry is a network instance connection. All traffic destined for the destination CIDR block is forwarded to the specified network instance connection.
   * 
   * @example
   * BlackHole
   */
  transitRouterRouteEntryNextHopType?: string;
  /**
   * @remarks
   * The instance ID of the origin of the route entry.
   * 
   * @example
   * vpc-m5ent6du8deaq5*****
   */
  transitRouterRouteEntryOriginResourceId?: string;
  /**
   * @remarks
   * The type of the origin instance of the route entry.
   * 
   * - **VPC**: Virtual Private Cloud (VPC) instance.
   * - **VBR**: Virtual Border Router (VBR) instance.
   * - **TR**: transit router instance.
   * - **VPN**: IPsec connection instance.
   * 
   * @example
   * VPC
   */
  transitRouterRouteEntryOriginResourceType?: string;
  /**
   * @remarks
   * The status of the route entry.
   * 
   * - **Active**: active.
   * - **Rejected**: rejected due to a route conflict.
   * - **Prohibited**: prohibited by a routing policy.
   * - **Standby**: standby.
   * - **Candidate**: candidate.
   * - **Creating**: being created.
   * - **Deleting**: being deleted.
   * 
   * @example
   * Active
   */
  transitRouterRouteEntryStatus?: string;
  /**
   * @remarks
   * The type of the route entry.
   * 
   * - **Static**: a statically configured route entry.
   * - **Propagated**: a route entry generated by automatic learning.
   * 
   * @example
   * Static
   */
  transitRouterRouteEntryType?: string;
  static names(): { [key: string]: string } {
    return {
      createTime: 'CreateTime',
      operationalMode: 'OperationalMode',
      pathAttributes: 'PathAttributes',
      prefixListId: 'PrefixListId',
      tag: 'Tag',
      transitRouterRouteEntryDescription: 'TransitRouterRouteEntryDescription',
      transitRouterRouteEntryDestinationCidrBlock: 'TransitRouterRouteEntryDestinationCidrBlock',
      transitRouterRouteEntryId: 'TransitRouterRouteEntryId',
      transitRouterRouteEntryName: 'TransitRouterRouteEntryName',
      transitRouterRouteEntryNextHopId: 'TransitRouterRouteEntryNextHopId',
      transitRouterRouteEntryNextHopResourceId: 'TransitRouterRouteEntryNextHopResourceId',
      transitRouterRouteEntryNextHopResourceType: 'TransitRouterRouteEntryNextHopResourceType',
      transitRouterRouteEntryNextHopType: 'TransitRouterRouteEntryNextHopType',
      transitRouterRouteEntryOriginResourceId: 'TransitRouterRouteEntryOriginResourceId',
      transitRouterRouteEntryOriginResourceType: 'TransitRouterRouteEntryOriginResourceType',
      transitRouterRouteEntryStatus: 'TransitRouterRouteEntryStatus',
      transitRouterRouteEntryType: 'TransitRouterRouteEntryType',
    };
  }

  static types(): { [key: string]: any } {
    return {
      createTime: 'string',
      operationalMode: 'boolean',
      pathAttributes: ListTransitRouterRouteEntriesResponseBodyTransitRouterRouteEntriesPathAttributes,
      prefixListId: 'string',
      tag: 'string',
      transitRouterRouteEntryDescription: 'string',
      transitRouterRouteEntryDestinationCidrBlock: 'string',
      transitRouterRouteEntryId: 'string',
      transitRouterRouteEntryName: 'string',
      transitRouterRouteEntryNextHopId: 'string',
      transitRouterRouteEntryNextHopResourceId: 'string',
      transitRouterRouteEntryNextHopResourceType: 'string',
      transitRouterRouteEntryNextHopType: 'string',
      transitRouterRouteEntryOriginResourceId: 'string',
      transitRouterRouteEntryOriginResourceType: 'string',
      transitRouterRouteEntryStatus: 'string',
      transitRouterRouteEntryType: 'string',
    };
  }

  validate() {
    if(this.pathAttributes && typeof (this.pathAttributes as any).validate === 'function') {
      (this.pathAttributes as any).validate();
    }
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

export class ListTransitRouterRouteEntriesResponseBody extends $dara.Model {
  /**
   * @remarks
   * The number of entries per page when entries are returned in pages.
   * 
   * @example
   * 20
   */
  maxResults?: number;
  /**
   * @remarks
   * The token that determines the start point of the next query. Valid values:
   * 
   * - If **NextToken** is empty, no subsequent query is to be sent.
   * - If **NextToken** is returned, the value indicates the token for the next query.
   * 
   * @example
   * fce19****
   */
  nextToken?: string;
  /**
   * @remarks
   * The request ID.
   * 
   * @example
   * C3835E5E-1504-4344-B1BB-98A4110F1079
   */
  requestId?: string;
  /**
   * @remarks
   * The total number of entries.
   * 
   * @example
   * 6
   */
  totalCount?: number;
  /**
   * @remarks
   * The list of route entries.
   */
  transitRouterRouteEntries?: ListTransitRouterRouteEntriesResponseBodyTransitRouterRouteEntries[];
  static names(): { [key: string]: string } {
    return {
      maxResults: 'MaxResults',
      nextToken: 'NextToken',
      requestId: 'RequestId',
      totalCount: 'TotalCount',
      transitRouterRouteEntries: 'TransitRouterRouteEntries',
    };
  }

  static types(): { [key: string]: any } {
    return {
      maxResults: 'number',
      nextToken: 'string',
      requestId: 'string',
      totalCount: 'number',
      transitRouterRouteEntries: { 'type': 'array', 'itemType': ListTransitRouterRouteEntriesResponseBodyTransitRouterRouteEntries },
    };
  }

  validate() {
    if(Array.isArray(this.transitRouterRouteEntries)) {
      $dara.Model.validateArray(this.transitRouterRouteEntries);
    }
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

