// This file is auto-generated, don't edit it
import * as $dara from '@darabonba/typescript';


export class ResetAgenticApiKeyResponseBodyData extends $dara.Model {
  /**
   * @remarks
   * The ID of the Agent to which the Access Token belongs.
   * 
   * @example
   * agent-7f3c9a2b
   */
  agentId?: string;
  /**
   * @remarks
   * The name of the Agent to which the Access Token belongs.
   * 
   * @example
   * my-data-agent
   */
  agentName?: string;
  /**
   * @remarks
   * The type of the Agent to which the Access Token belongs. Valid values:
   * - HUMAN_BOUND: fully inherits the permissions of the associated user.
   * - PERMISSION_NARROW: narrows the permissions based on the associated user\\"s permission baseline.
   * - AGENT_BOUND: inherits the permissions of the parent Agent.
   * - STANDALONE: holds permissions as an independent identity principal.
   * 
   * @example
   * STANDALONE
   */
  agentType?: string;
  /**
   * @remarks
   * The time when the Access Token was created, in the yyyy-MM-dd HH:mm:ss format (UTC+8). This value remains unchanged after the reset.
   * 
   * @example
   * 2026-05-13 08:00:00
   */
  createdAt?: string;
  /**
   * @remarks
   * The user ID of the Access Token creator.
   * 
   * @example
   * 27400000000000001
   */
  creatorId?: string;
  /**
   * @remarks
   * The display name of the Access Token creator.
   * 
   * @example
   * alice
   */
  creatorName?: string;
  /**
   * @remarks
   * The description of the Access Token. This value remains unchanged after the reset.
   * 
   * @example
   * Access token used by the data analysis agent
   */
  description?: string;
  /**
   * @remarks
   * The expiration time of the Access Token, in the yyyy-MM-dd HH:mm:ss format (UTC+8). If ExpireAfterSeconds is specified, the expiration time is recalculated from the time of the reset. If ExpireAfterSeconds is not specified, the original expiration time is retained.
   * 
   * @example
   * 2027-05-13 10:20:30
   */
  expireTime?: string;
  /**
   * @remarks
   * The ID of the reset Access Token. This value remains unchanged after the reset.
   * 
   * @example
   * 1024
   */
  id?: number;
  /**
   * @remarks
   * Indicates whether the Access Token has been revoked. An Access Token returned after a successful reset is always in the non-revoked state (false).
   */
  isRevoked?: boolean;
  /**
   * @remarks
   * The visible prefix of the Access Token, which is used to identify the Access Token without exposing the full Secret. This value remains unchanged after the reset.
   * 
   * @example
   * dms_sk_3f9a
   */
  keyPrefix?: string;
  /**
   * @remarks
   * The time when the Access Token was last used, in the yyyy-MM-dd HH:mm:ss format (UTC+8). This value is empty if the Access Token has never been used.
   * 
   * @example
   * 2026-05-13 09:15:00
   */
  lastUsedTime?: string;
  /**
   * @remarks
   * The name of the Access Token. This value remains unchanged after the reset.
   * 
   * @example
   * prod-readonly-key
   */
  name?: string;
  /**
   * @remarks
   * The new plaintext Secret generated by this reset. This value is returned only once in this response and will not be returned by any subsequent operation. Store it securely right away. The old Secret becomes invalid immediately after the reset.
   * 
   * @example
   * dms_sk_3f9a1c8e5b7d4062a1f6c9e2b8d05a3f
   */
  secret?: string;
  /**
   * @remarks
   * The credential source of the Access Token. The reset operation supports only Access Tokens issued by the console. Therefore, the value is always console.
   * 
   * @example
   * console
   */
  source?: string;
  /**
   * @remarks
   * The reminder information related to this reset, such as a notice that the new Secret is returned only once and must be stored immediately. This value is empty if no reminder exists.
   * 
   * @example
   * The new secret is shown only once. Please store it securely now.
   */
  warning?: string;
  static names(): { [key: string]: string } {
    return {
      agentId: 'AgentId',
      agentName: 'AgentName',
      agentType: 'AgentType',
      createdAt: 'CreatedAt',
      creatorId: 'CreatorId',
      creatorName: 'CreatorName',
      description: 'Description',
      expireTime: 'ExpireTime',
      id: 'Id',
      isRevoked: 'IsRevoked',
      keyPrefix: 'KeyPrefix',
      lastUsedTime: 'LastUsedTime',
      name: 'Name',
      secret: 'Secret',
      source: 'Source',
      warning: 'Warning',
    };
  }

  static types(): { [key: string]: any } {
    return {
      agentId: 'string',
      agentName: 'string',
      agentType: 'string',
      createdAt: 'string',
      creatorId: 'string',
      creatorName: 'string',
      description: 'string',
      expireTime: 'string',
      id: 'number',
      isRevoked: 'boolean',
      keyPrefix: 'string',
      lastUsedTime: 'string',
      name: 'string',
      secret: 'string',
      source: 'string',
      warning: 'string',
    };
  }

  validate() {
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

export class ResetAgenticApiKeyResponseBody extends $dara.Model {
  /**
   * @remarks
   * The Access Token information returned after a successful reset. The Secret field contains the new plaintext Secret, which is returned only once in this response.
   */
  data?: ResetAgenticApiKeyResponseBodyData;
  /**
   * @remarks
   * The error code returned when the request fails. You can use this code to programmatically determine the failure type. This value is empty when the request succeeds.
   * 
   * @example
   * ACCESS_TOKEN_NOT_FOUND
   */
  errorCode?: string;
  /**
   * @remarks
   * The error message returned when the request fails. This message helps you locate the issue. This value is empty when the request succeeds.
   * 
   * @example
   * access token not found: 1024
   */
  errorMessage?: string;
  /**
   * @remarks
   * The unique request ID, which is used for troubleshooting and log correlation.
   * 
   * @example
   * 1AD222E9-E606-4A42-BF6C-2C4DD51BD5E7
   */
  requestId?: string;
  /**
   * @remarks
   * Indicates whether the request was successful. A value of true indicates that the reset was successful. A value of false indicates a failure. In this case, check ErrorCode and ErrorMessage to identify the cause.
   */
  success?: boolean;
  static names(): { [key: string]: string } {
    return {
      data: 'Data',
      errorCode: 'ErrorCode',
      errorMessage: 'ErrorMessage',
      requestId: 'RequestId',
      success: 'Success',
    };
  }

  static types(): { [key: string]: any } {
    return {
      data: ResetAgenticApiKeyResponseBodyData,
      errorCode: 'string',
      errorMessage: 'string',
      requestId: 'string',
      success: 'boolean',
    };
  }

  validate() {
    if(this.data && typeof (this.data as any).validate === 'function') {
      (this.data as any).validate();
    }
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

