// This file is auto-generated, don't edit it
import * as $dara from '@darabonba/typescript';


export class DescribeDefenseRuleResponseBodyRule extends $dara.Model {
  /**
   * @remarks
   * The details of the protection rule, which is a string converted from a JSON object constructed with a series of parameters. For more information, refer to the **protection rule parameter description** in [CreateDefenseRule](https://help.aliyun.com/document_detail/461421.html).
   * 
   * @example
   * {\\"status\\":1,\\"policyId\\":1012,\\"action\\":\\"block\\"}
   */
  config?: string;
  /**
   * @remarks
   * The origin of the protection rule. Valid values:
   * 
   * - **custom**: user-defined.
   * 
   * - **system**: automatically generated by the system.
   * 
   * @example
   * custom
   */
  defenseOrigin?: string;
  /**
   * @remarks
   * The protection scenario.
   * 
   * When the **DefenseType** parameter is set to **template**, valid values:
   * - **waf_group**: regex rules for basic protection.
   * - **waf_base**: new Web core protection.
   * - **waf_base_compliance**: protocol compliance rules for basic protection.
   * - **waf_base_sema**: semantic rules for basic protection.
   * - **cc**: HTTP flood protection.
   * - **antiscan_dirscan**: directory traversal blocking in scan protection.
   * - **antiscan_highfreq**: high-frequency scan blocking in scan protection.
   * - **antiscan_scantools**: scan tool blocking in scan protection.
   * - **ip_blacklist**: IP blacklist.
   * - **custom_acl**: custom rules.
   * - **region_block**: location blacklist.
   * - **tamperproof**: web tamper proofing.
   * - **dlp**: information leak prevention.
   * - **custom_response_block**: custom response.
   * - **spike_throttle**: peak traffic throttling.
   * 
   * When the **DefenseType** parameter is set to **resource**, valid values:
   * 
   * - **account_identifier**: account extraction.
   * - **custom_response**: new custom response.
   * - **waf_codec**: decoding.
   * 
   * When the **DefenseType** parameter is set to **global**, valid values:
   * 
   * - **regular_custom**: custom regex.
   * - **address_book**: address book.
   * - **custom_response**: new custom response.
   * 
   * @example
   * waf_group
   */
  defenseScene?: string;
  /**
   * @remarks
   * The type of the protection rule. Valid values:
   * 
   * - **template** (default): template protection rule.
   * 
   * - **resource**: protection object-level rule.
   * - **global**: global-level rule.
   * 
   * @example
   * template
   */
  defenseType?: string;
  /**
   * @remarks
   * The time when the protection rule was last modified.
   * 
   * @example
   * 1665196746000
   */
  gmtModified?: number;
  /**
   * @remarks
   * The protected object to which the rule belongs.
   * > This parameter is returned only when **DefenseType** is set to **resource**.
   * 
   * @example
   * rencs***-waf
   */
  resource?: string;
  /**
   * @remarks
   * The ID of the protection rule.
   * 
   * @example
   * 2732975
   */
  ruleId?: number;
  /**
   * @remarks
   * The name of the protection rule.
   * 
   * @example
   * test1
   */
  ruleName?: string;
  /**
   * @remarks
   * The status of the protection rule. Valid values:
   * 
   * - **0**: Disabled.
   * 
   * - **1**: Enabled.
   * 
   * @example
   * 1
   */
  status?: number;
  /**
   * @remarks
   * The ID of the protection rule template.
   * > This parameter is returned only when **DefenseType** is set to **template**.
   * 
   * @example
   * 9114
   */
  templateId?: number;
  static names(): { [key: string]: string } {
    return {
      config: 'Config',
      defenseOrigin: 'DefenseOrigin',
      defenseScene: 'DefenseScene',
      defenseType: 'DefenseType',
      gmtModified: 'GmtModified',
      resource: 'Resource',
      ruleId: 'RuleId',
      ruleName: 'RuleName',
      status: 'Status',
      templateId: 'TemplateId',
    };
  }

  static types(): { [key: string]: any } {
    return {
      config: 'string',
      defenseOrigin: 'string',
      defenseScene: 'string',
      defenseType: 'string',
      gmtModified: 'number',
      resource: 'string',
      ruleId: 'number',
      ruleName: 'string',
      status: 'number',
      templateId: 'number',
    };
  }

  validate() {
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

export class DescribeDefenseRuleResponseBody extends $dara.Model {
  /**
   * @remarks
   * The request ID.
   * 
   * @example
   * D7861F61-5B61-46CE-A47C-6B19160D5EB0
   */
  requestId?: string;
  /**
   * @remarks
   * The rule configuration, which is a string converted from a JSON object constructed with a series of parameters.
   */
  rule?: DescribeDefenseRuleResponseBodyRule;
  static names(): { [key: string]: string } {
    return {
      requestId: 'RequestId',
      rule: 'Rule',
    };
  }

  static types(): { [key: string]: any } {
    return {
      requestId: 'string',
      rule: DescribeDefenseRuleResponseBodyRule,
    };
  }

  validate() {
    if(this.rule && typeof (this.rule as any).validate === 'function') {
      (this.rule as any).validate();
    }
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

