// This file is auto-generated, don't edit it
import * as $dara from '@darabonba/typescript';


export class CreateCheckItemResponseBodyData extends $dara.Model {
  /**
   * @remarks
   * The ID of the check item returned upon successful creation.
   * 
   * @example
   * 100000000001
   */
  checkId?: number;
  static names(): { [key: string]: string } {
    return {
      checkId: 'CheckId',
    };
  }

  static types(): { [key: string]: any } {
    return {
      checkId: 'number',
    };
  }

  validate() {
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

export class CreateCheckItemResponseBody extends $dara.Model {
  /**
   * @remarks
   * The data returned if the call is successful.
   */
  data?: CreateCheckItemResponseBodyData;
  /**
   * @remarks
   * The request ID, which is a unique identifier generated by Alibaba Cloud for the request. You can use this ID to troubleshoot issues.
   * 
   * @example
   * F8B6F758-BCD4-597A-8A2C-DA5A552C****
   */
  requestId?: string;
  static names(): { [key: string]: string } {
    return {
      data: 'Data',
      requestId: 'RequestId',
    };
  }

  static types(): { [key: string]: any } {
    return {
      data: CreateCheckItemResponseBodyData,
      requestId: 'string',
    };
  }

  validate() {
    if(this.data && typeof (this.data as any).validate === 'function') {
      (this.data as any).validate();
    }
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

