// This file is auto-generated, don't edit it
import * as $dara from '@darabonba/typescript';


export class DescribeGroupedTagsResponseBodyGroupedFileds extends $dara.Model {
  /**
   * @remarks
   * The number of assets associated with the tag.
   * 
   * @example
   * 152
   */
  count?: string;
  /**
   * @remarks
   * The tag name.
   * 
   * @example
   * InternetIp
   */
  name?: string;
  /**
   * @remarks
   * The tag ID.
   * 
   * @example
   * 3252366
   */
  tagId?: number;
  static names(): { [key: string]: string } {
    return {
      count: 'Count',
      name: 'Name',
      tagId: 'TagId',
    };
  }

  static types(): { [key: string]: any } {
    return {
      count: 'string',
      name: 'string',
      tagId: 'number',
    };
  }

  validate() {
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

export class DescribeGroupedTagsResponseBody extends $dara.Model {
  /**
   * @remarks
   * This parameter is deprecated and can be ignored.
   * 
   * @example
   * 0
   */
  count?: number;
  /**
   * @remarks
   * The statistics information of asset labels.
   */
  groupedFileds?: DescribeGroupedTagsResponseBodyGroupedFileds[];
  /**
   * @remarks
   * The HTTP status code of the request.
   * 
   * @example
   * 200
   */
  httpStatusCode?: number;
  /**
   * @remarks
   * The request ID. It is a unique identifier generated by Alibaba Cloud for the request and can be used to troubleshoot issues.
   * 
   * @example
   * 151F6EB6-D5F3-417A-AF7B-4D84975DB586
   */
  requestId?: string;
  /**
   * @remarks
   * Indicates whether the request was successful. Valid values:
   * 
   * - **true**: The request was successful.
   * - **false**: The request failed.
   * 
   * @example
   * true
   */
  success?: boolean;
  static names(): { [key: string]: string } {
    return {
      count: 'Count',
      groupedFileds: 'GroupedFileds',
      httpStatusCode: 'HttpStatusCode',
      requestId: 'RequestId',
      success: 'Success',
    };
  }

  static types(): { [key: string]: any } {
    return {
      count: 'number',
      groupedFileds: { 'type': 'array', 'itemType': DescribeGroupedTagsResponseBodyGroupedFileds },
      httpStatusCode: 'number',
      requestId: 'string',
      success: 'boolean',
    };
  }

  validate() {
    if(Array.isArray(this.groupedFileds)) {
      $dara.Model.validateArray(this.groupedFileds);
    }
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

