// This file is auto-generated, don't edit it
import * as $dara from '@darabonba/typescript';


export class DescribeExposedInstanceCriteriaResponseBodyCriteriaList extends $dara.Model {
  /**
   * @remarks
   * The name of the query condition.
   * 
   * @example
   * instanceId
   */
  name?: string;
  /**
   * @remarks
   * The type of the query condition. Valid values:
   * - **input**: requires manual input of the query content.
   * - **select**: requires selecting a value from the options list (the **Values** field).
   * 
   * @example
   * select
   */
  type?: string;
  /**
   * @remarks
   * The available option values when **Type** (the type of the query condition) is **select**.
   * > When **Type** (the type of the query condition) is **input**, this parameter returns an empty value.
   * 
   * @example
   * i-bp19r0fdd39idxhf****
   */
  values?: string;
  static names(): { [key: string]: string } {
    return {
      name: 'Name',
      type: 'Type',
      values: 'Values',
    };
  }

  static types(): { [key: string]: any } {
    return {
      name: 'string',
      type: 'string',
      values: 'string',
    };
  }

  validate() {
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

export class DescribeExposedInstanceCriteriaResponseBody extends $dara.Model {
  /**
   * @remarks
   * The supported query conditions for querying exposed assets.
   */
  criteriaList?: DescribeExposedInstanceCriteriaResponseBodyCriteriaList[];
  /**
   * @remarks
   * The request ID, which is a unique identifier generated by Alibaba Cloud for the request. You can use this ID to troubleshoot issues.
   * 
   * @example
   * 6D9CDB47-6191-4415-BE63-7E8B12CD4FBE
   */
  requestId?: string;
  static names(): { [key: string]: string } {
    return {
      criteriaList: 'CriteriaList',
      requestId: 'RequestId',
    };
  }

  static types(): { [key: string]: any } {
    return {
      criteriaList: { 'type': 'array', 'itemType': DescribeExposedInstanceCriteriaResponseBodyCriteriaList },
      requestId: 'string',
    };
  }

  validate() {
    if(Array.isArray(this.criteriaList)) {
      $dara.Model.validateArray(this.criteriaList);
    }
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

