// This file is auto-generated, don't edit it
import * as $dara from '@darabonba/typescript';


export class DescribeWebLockBindListResponseBodyBindList extends $dara.Model {
  /**
   * @remarks
   * The number of alerts.
   * 
   * @example
   * 2
   */
  auditCount?: string;
  /**
   * @remarks
   * The number of blocked events.
   * 
   * @example
   * 10
   */
  blockCount?: string;
  /**
   * @remarks
   * The number of protected directories.
   * 
   * @example
   * 5
   */
  dirCount?: string;
  /**
   * @remarks
   * The name of the server.
   * 
   * @example
   * testName
   */
  instanceName?: string;
  /**
   * @remarks
   * The public IP address of the server.
   * 
   * @example
   * 54.169.XX.XX
   */
  internetIp?: string;
  /**
   * @remarks
   * The private IP address of the server.
   * 
   * @example
   * 192.168.XX.XX
   */
  intranetIp?: string;
  /**
   * @remarks
   * The operating system type of the server.
   * 
   * @example
   * Linux
   */
  os?: string;
  /**
   * @remarks
   * The startup progress of web tamper-proofing protection, in percentage. Value range: 0 to 100%.
   * 
   * @example
   * 99
   */
  percent?: number;
  /**
   * @remarks
   * The error code for the web tamper-proofing service exception. Valid values:
   * - **2001**: The client is offline.
   * - **9999**: The connection timeout.
   * 
   * @example
   * 2001
   */
  serviceCode?: string;
  /**
   * @remarks
   * The details of the web tamper-proofing service exception. Valid values:
   * - **client offline**: The client is offline.
   * - **timeout**: The connection timeout.
   * 
   * @example
   * client offline
   */
  serviceDetail?: string;
  /**
   * @remarks
   * The web tamper-proofing service status of the server. Valid values:
   * - **stop**: The tamper-proofing service is not started.
   * - **initializing**: The tamper-proofing service is starting.
   * - **exception**: The tamper-proofing service is abnormal.
   * - **running**: The tamper-proofing service is running.
   * - **closing**: The tamper-proofing service is undergoing shutdown.
   * 
   * @example
   * stop
   */
  serviceStatus?: string;
  /**
   * @remarks
   * The protection status of the server. Valid values:
   * - **on**: Protection is enabled.
   * - **off**: Protection is disabled.
   * 
   * @example
   * on
   */
  status?: string;
  /**
   * @remarks
   * The UUID of the server.
   * 
   * @example
   * inet-12345****
   */
  uuid?: string;
  static names(): { [key: string]: string } {
    return {
      auditCount: 'AuditCount',
      blockCount: 'BlockCount',
      dirCount: 'DirCount',
      instanceName: 'InstanceName',
      internetIp: 'InternetIp',
      intranetIp: 'IntranetIp',
      os: 'Os',
      percent: 'Percent',
      serviceCode: 'ServiceCode',
      serviceDetail: 'ServiceDetail',
      serviceStatus: 'ServiceStatus',
      status: 'Status',
      uuid: 'Uuid',
    };
  }

  static types(): { [key: string]: any } {
    return {
      auditCount: 'string',
      blockCount: 'string',
      dirCount: 'string',
      instanceName: 'string',
      internetIp: 'string',
      intranetIp: 'string',
      os: 'string',
      percent: 'number',
      serviceCode: 'string',
      serviceDetail: 'string',
      serviceStatus: 'string',
      status: 'string',
      uuid: 'string',
    };
  }

  validate() {
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

export class DescribeWebLockBindListResponseBody extends $dara.Model {
  /**
   * @remarks
   * The collection of servers that have web tamper-proofing protection enabled.
   */
  bindList?: DescribeWebLockBindListResponseBodyBindList[];
  /**
   * @remarks
   * The page number of the current page in a paging query. Minimum value: 1. Default value: 1.
   * 
   * @example
   * 1
   */
  currentPage?: number;
  /**
   * @remarks
   * The maximum number of entries per page in a paging query. Default value: 20.
   * 
   * @example
   * 20
   */
  pageSize?: number;
  /**
   * @remarks
   * The ID of the request. The China value is a unique identifier generated by Alibaba Cloud for the request and can be used for troubleshooting.
   * 
   * @example
   * D9354C1A-D709-4873-9AAE-41513327B247
   */
  requestId?: string;
  /**
   * @remarks
   * The total number of servers attached to web tamper-proofing.
   * 
   * @example
   * 11409
   */
  totalCount?: number;
  static names(): { [key: string]: string } {
    return {
      bindList: 'BindList',
      currentPage: 'CurrentPage',
      pageSize: 'PageSize',
      requestId: 'RequestId',
      totalCount: 'TotalCount',
    };
  }

  static types(): { [key: string]: any } {
    return {
      bindList: { 'type': 'array', 'itemType': DescribeWebLockBindListResponseBodyBindList },
      currentPage: 'number',
      pageSize: 'number',
      requestId: 'string',
      totalCount: 'number',
    };
  }

  validate() {
    if(Array.isArray(this.bindList)) {
      $dara.Model.validateArray(this.bindList);
    }
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

