// This file is auto-generated, don't edit it
import * as $dara from '@darabonba/typescript';


export class DescribeStrictEventNameResponseBodyData extends $dara.Model {
  /**
   * @remarks
   * Alarm name.
   * 
   * @example
   * System log abnormal deletion
   */
  eventName?: string;
  /**
   * @remarks
   * Alarm type.
   * 
   * @example
   * Suspicious Process
   */
  eventType?: string;
  /**
   * @remarks
   * Displayed alarm name.
   * 
   * @example
   * Suspicious Process
   */
  showEventName?: string;
  /**
   * @remarks
   * Displayed alarm type.
   * 
   * @example
   * System log abnormal deletion
   */
  showEventType?: string;
  /**
   * @remarks
   * Indicates whether the user has enabled the strict mode for this alarm type.
   * - true: Enabled
   * - false: Not enabled
   * 
   * @example
   * true
   */
  switchConfig?: boolean;
  static names(): { [key: string]: string } {
    return {
      eventName: 'EventName',
      eventType: 'EventType',
      showEventName: 'ShowEventName',
      showEventType: 'ShowEventType',
      switchConfig: 'SwitchConfig',
    };
  }

  static types(): { [key: string]: any } {
    return {
      eventName: 'string',
      eventType: 'string',
      showEventName: 'string',
      showEventType: 'string',
      switchConfig: 'boolean',
    };
  }

  validate() {
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

export class DescribeStrictEventNameResponseBody extends $dara.Model {
  /**
   * @remarks
   * Returned data.
   */
  data?: DescribeStrictEventNameResponseBodyData[];
  /**
   * @remarks
   * The ID of this call request, a unique identifier generated by Alibaba Cloud for this request, which can be used to troubleshoot and locate issues.
   * 
   * @example
   * D65AADFC-1D20-5A6A-8F6A-9FA53C0D****
   */
  requestId?: string;
  static names(): { [key: string]: string } {
    return {
      data: 'Data',
      requestId: 'RequestId',
    };
  }

  static types(): { [key: string]: any } {
    return {
      data: { 'type': 'array', 'itemType': DescribeStrictEventNameResponseBodyData },
      requestId: 'string',
    };
  }

  validate() {
    if(Array.isArray(this.data)) {
      $dara.Model.validateArray(this.data);
    }
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

