// This file is auto-generated, don't edit it
import * as $dara from '@darabonba/typescript';


export class DescribeSecurityCheckScheduleConfigResponseBodyRiskCheckJobConfig extends $dara.Model {
  /**
   * @remarks
   * The check cycle. Valid values: Monday to Sunday. You can specify multiple days. Separate multiple days with commas (,).
   * 
   * - **1**: Monday
   * - **2**: Tuesday
   * - **3**: Wednesday
   * - **4**: Thursday
   * - **5**: Friday
   * - **6**: Saturday
   * - **7**: Sunday
   * 
   * @example
   * 1,2,3
   */
  daysOfWeek?: string;
  /**
   * @remarks
   * The check end time.
   * 
   * - **6**: The check ends between 00:00 and 06:00.
   * - **12**: The check ends between 06:00 and 12:00.
   * - **18**: The check ends between 12:00 and 18:00.
   * - **24**: The check ends between 18:00 and 24:00.
   * 
   * Unit: hours. The value is an on-the-hour value of the current day (0 to 24).
   * 
   * @example
   * 12
   */
  endTime?: number;
  /**
   * @remarks
   * The check start time.
   * 
   * - **0**: The check starts between 00:00 and 06:00.
   * - **6**: The check starts between 06:00 and 12:00.
   * - **12**: The check starts between 12:00 and 18:00.
   * - **18**: The check starts between 18:00 and 24:00.
   * 
   * Unit: hours. The value is an on-the-hour value of the current day (0 to 24).
   * 
   * @example
   * 6
   */
  startTime?: number;
  static names(): { [key: string]: string } {
    return {
      daysOfWeek: 'DaysOfWeek',
      endTime: 'EndTime',
      startTime: 'StartTime',
    };
  }

  static types(): { [key: string]: any } {
    return {
      daysOfWeek: 'string',
      endTime: 'number',
      startTime: 'number',
    };
  }

  validate() {
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

export class DescribeSecurityCheckScheduleConfigResponseBody extends $dara.Model {
  /**
   * @remarks
   * The request ID. It is a unique identifier generated by Alibaba Cloud for the request and can be used for troubleshooting.
   * 
   * @example
   * 48D2E9A9-A1B0-4295-B727-0995757C47E9
   */
  requestId?: string;
  /**
   * @remarks
   * The detailed configuration of the custom check settings.
   */
  riskCheckJobConfig?: DescribeSecurityCheckScheduleConfigResponseBodyRiskCheckJobConfig;
  static names(): { [key: string]: string } {
    return {
      requestId: 'RequestId',
      riskCheckJobConfig: 'RiskCheckJobConfig',
    };
  }

  static types(): { [key: string]: any } {
    return {
      requestId: 'string',
      riskCheckJobConfig: DescribeSecurityCheckScheduleConfigResponseBodyRiskCheckJobConfig,
    };
  }

  validate() {
    if(this.riskCheckJobConfig && typeof (this.riskCheckJobConfig as any).validate === 'function') {
      (this.riskCheckJobConfig as any).validate();
    }
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

