// This file is auto-generated, don't edit it
import * as $dara from '@darabonba/typescript';


export class GenerateClusterScannerWebhookYamlResponseBody extends $dara.Model {
  /**
   * @remarks
   * The ID of the container cluster.
   * 
   * @example
   * c471f0f61b9c04f8380556e922cf1****
   */
  clusterId?: string;
  /**
   * @remarks
   * Unique identifier.
   * 
   * @example
   * 131231
   */
  id?: number;
  /**
   * @remarks
   * The ID of the current request, which is a unique identifier generated by Alibaba Cloud for this request and can be used for troubleshooting and problem localization.
   * 
   * @example
   * BE120DAB-F4E7-4C53-ADC3-A97578ABF384
   */
  requestId?: string;
  /**
   * @remarks
   * Indicates whether the incremental scan switch is enabled.
   * 
   * @example
   * 1
   */
  webhookOpen?: number;
  static names(): { [key: string]: string } {
    return {
      clusterId: 'ClusterId',
      id: 'Id',
      requestId: 'RequestId',
      webhookOpen: 'WebhookOpen',
    };
  }

  static types(): { [key: string]: any } {
    return {
      clusterId: 'string',
      id: 'number',
      requestId: 'string',
      webhookOpen: 'number',
    };
  }

  validate() {
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

