// This file is auto-generated, don't edit it
import * as $dara from '@darabonba/typescript';


export class GenerateOnceTaskResponseBody extends $dara.Model {
  /**
   * @remarks
   * Indicates whether you can create more scan tasks. Valid values:
   * 
   * - **true**: You can create more scan tasks.
   * 
   * - **false**: You cannot create more scan tasks.
   * 
   * > You can run up to 10 concurrent scan tasks. Requests to create a new task fail if this limit is exceeded. Wait for an existing task to complete before creating a new one.
   * 
   * @example
   * true
   */
  canCreate?: boolean;
  /**
   * @remarks
   * The collection time.
   * 
   * @example
   * 1670307567000
   */
  collectTime?: number;
  /**
   * @remarks
   * The number of completed tasks.
   * 
   * @example
   * 61
   */
  finishCount?: number;
  /**
   * @remarks
   * The ID of the last task.
   * 
   * @example
   * 38730bb078f4a1461d4ed283994c****
   */
  lastTask?: string;
  /**
   * @remarks
   * The request ID. This unique identifier is generated by Alibaba Cloud and can be used for troubleshooting.
   * 
   * @example
   * 8BB6B8FA-39E8-5654-A309-8EED13B1****
   */
  requestId?: string;
  /**
   * @remarks
   * The ID of the scan task.
   * 
   * @example
   * 38730bb078f4a1461d4ed283994c****
   */
  taskId?: string;
  /**
   * @remarks
   * The total number of tasks.
   * 
   * @example
   * 100
   */
  totalCount?: number;
  static names(): { [key: string]: string } {
    return {
      canCreate: 'CanCreate',
      collectTime: 'CollectTime',
      finishCount: 'FinishCount',
      lastTask: 'LastTask',
      requestId: 'RequestId',
      taskId: 'TaskId',
      totalCount: 'TotalCount',
    };
  }

  static types(): { [key: string]: any } {
    return {
      canCreate: 'boolean',
      collectTime: 'number',
      finishCount: 'number',
      lastTask: 'string',
      requestId: 'string',
      taskId: 'string',
      totalCount: 'number',
    };
  }

  validate() {
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

