// This file is auto-generated, don't edit it
import * as $dara from '@darabonba/typescript';


export class GetInstallCodeForUuidResponseBodyInstallCode extends $dara.Model {
  /**
   * @remarks
   * Installation verification code for manually installing the Cloud Security Center client.
   * 
   * @example
   * AK1W**
   */
  captchaCode?: string;
  /**
   * @remarks
   * Expiration date of the installation verification code. The format is a 13-digit timestamp.
   * > The installation verification code can only be used within its validity period. Expired codes cannot be used.
   * 
   * @example
   * 1723860871689
   */
  expiredDate?: number;
  /**
   * @remarks
   * Server group ID.
   * 
   * @example
   * 342710
   */
  groupId?: number;
  /**
   * @remarks
   * Server group name.
   * 
   * @example
   * TestGroup
   */
  groupName?: string;
  /**
   * @remarks
   * Operating system of the server. Values:
   * 
   * - **linux**: Linux
   * 
   * - **windows**: Windows
   * 
   * @example
   * linux
   */
  os?: string;
  /**
   * @remarks
   * Name of the server vendor.
   * 
   * @example
   * ALIYUN
   */
  vendorName?: string;
  static names(): { [key: string]: string } {
    return {
      captchaCode: 'CaptchaCode',
      expiredDate: 'ExpiredDate',
      groupId: 'GroupId',
      groupName: 'GroupName',
      os: 'Os',
      vendorName: 'VendorName',
    };
  }

  static types(): { [key: string]: any } {
    return {
      captchaCode: 'string',
      expiredDate: 'number',
      groupId: 'number',
      groupName: 'string',
      os: 'string',
      vendorName: 'string',
    };
  }

  validate() {
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

export class GetInstallCodeForUuidResponseBody extends $dara.Model {
  /**
   * @remarks
   * API status code.
   * 
   * @example
   * 200
   */
  code?: number;
  /**
   * @remarks
   * HTTP status code
   * 
   * @example
   * 200
   */
  httpStatusCode?: number;
  /**
   * @remarks
   * Client installation code.
   */
  installCode?: GetInstallCodeForUuidResponseBodyInstallCode;
  /**
   * @remarks
   * Response message from the request.
   * 
   * @example
   * successful
   */
  message?: string;
  /**
   * @remarks
   * The ID of the current request, a unique identifier generated by Alibaba Cloud for troubleshooting and issue localization.
   * 
   * @example
   * 7532B7EE-7CE7-5F4D-BF04-B12447DDCAE1
   */
  requestId?: string;
  /**
   * @remarks
   * The status of the returned query result. Values: - **true**: Success - **false**: Failure
   * 
   * @example
   * true
   */
  success?: boolean;
  static names(): { [key: string]: string } {
    return {
      code: 'Code',
      httpStatusCode: 'HttpStatusCode',
      installCode: 'InstallCode',
      message: 'Message',
      requestId: 'RequestId',
      success: 'Success',
    };
  }

  static types(): { [key: string]: any } {
    return {
      code: 'number',
      httpStatusCode: 'number',
      installCode: GetInstallCodeForUuidResponseBodyInstallCode,
      message: 'string',
      requestId: 'string',
      success: 'boolean',
    };
  }

  validate() {
    if(this.installCode && typeof (this.installCode as any).validate === 'function') {
      (this.installCode as any).validate();
    }
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

