// This file is auto-generated, don't edit it
import * as $dara from '@darabonba/typescript';


export class GetValidDeductInstancesResponseBodyDataDeductPackageList extends $dara.Model {
  /**
   * @remarks
   * Authorized consumption in the current billing cycle.
   * 
   * @example
   * 10
   */
  currentPeriodUsed?: number;
  /**
   * @remarks
   * End time.
   * 
   * @example
   * 1737734400000
   */
  endTime?: number;
  /**
   * @remarks
   * Total amount of the resource package.
   * 
   * @example
   * 1000
   */
  initCapacity?: number;
  /**
   * @remarks
   * Resource package instance ID.
   * 
   * @example
   * sas_**_dp_cn-2***
   */
  instanceId?: string;
  /**
   * @remarks
   * Module code. Values:
   * - **POST_HOST**: Host and container protection
   * - **CSPM**: Cloud product configuration check
   * - **VUL**: Vulnerability scan
   * 
   * @example
   * POST_HOST
   */
  module?: string;
  /**
   * @remarks
   * Authorized consumption up to the previous billing cycle.
   * 
   * @example
   * 100
   */
  periodCapacity?: number;
  /**
   * @remarks
   * Start timestamp (milliseconds).
   * 
   * @example
   * 1737734400000
   */
  startTime?: number;
  /**
   * @remarks
   * Resource package status. Values:
   * - **valid**: Valid
   * - **invalid**: Invalid
   * 
   * @example
   * Available
   */
  status?: string;
  static names(): { [key: string]: string } {
    return {
      currentPeriodUsed: 'CurrentPeriodUsed',
      endTime: 'EndTime',
      initCapacity: 'InitCapacity',
      instanceId: 'InstanceId',
      module: 'Module',
      periodCapacity: 'PeriodCapacity',
      startTime: 'StartTime',
      status: 'Status',
    };
  }

  static types(): { [key: string]: any } {
    return {
      currentPeriodUsed: 'number',
      endTime: 'number',
      initCapacity: 'number',
      instanceId: 'string',
      module: 'string',
      periodCapacity: 'number',
      startTime: 'number',
      status: 'string',
    };
  }

  validate() {
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

export class GetValidDeductInstancesResponseBodyData extends $dara.Model {
  /**
   * @remarks
   * Whether eligible for trial. Values:
   * - **true**: Eligible
   * - **false**: Not eligible
   * 
   * @example
   * true
   */
  canTry?: boolean;
  /**
   * @remarks
   * List of resource package usage details.
   */
  deductPackageList?: GetValidDeductInstancesResponseBodyDataDeductPackageList[];
  static names(): { [key: string]: string } {
    return {
      canTry: 'CanTry',
      deductPackageList: 'DeductPackageList',
    };
  }

  static types(): { [key: string]: any } {
    return {
      canTry: 'boolean',
      deductPackageList: { 'type': 'array', 'itemType': GetValidDeductInstancesResponseBodyDataDeductPackageList },
    };
  }

  validate() {
    if(Array.isArray(this.deductPackageList)) {
      $dara.Model.validateArray(this.deductPackageList);
    }
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

export class GetValidDeductInstancesResponseBody extends $dara.Model {
  /**
   * @remarks
   * Returned data.
   */
  data?: GetValidDeductInstancesResponseBodyData;
  /**
   * @remarks
   * The ID of this call request, a unique identifier generated by Alibaba Cloud for the request, which can be used to troubleshoot and locate issues.
   * 
   * @example
   * 6D56A5C4-9C78-5EB1-9246-60B7FAECA1D5
   */
  requestId?: string;
  static names(): { [key: string]: string } {
    return {
      data: 'Data',
      requestId: 'RequestId',
    };
  }

  static types(): { [key: string]: any } {
    return {
      data: GetValidDeductInstancesResponseBodyData,
      requestId: 'string',
    };
  }

  validate() {
    if(this.data && typeof (this.data as any).validate === 'function') {
      (this.data as any).validate();
    }
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

