// This file is auto-generated, don't edit it
import * as $dara from '@darabonba/typescript';


export class ListAutoTagRulesResponseBodyAutoTagRuleList extends $dara.Model {
  /**
   * @remarks
   * The Alibaba Cloud account ID.
   * 
   * @example
   * 558463566374****
   */
  aliUid?: number;
  /**
   * @remarks
   * The timestamp when the data was created. Unit: milliseconds.
   * 
   * @example
   * 1614674401000
   */
  createTimestamp?: number;
  /**
   * @remarks
   * The expression of the rule.
   * 
   * @example
   * [{\\"groups\\":\\"0\\",\\"fieldValueType\\":\\"string\\",\\"field\\":\\"internetIp\\",\\"operator\\":\\"equals\\",\\"value\\":\\"12.0.0.1\\"}]
   */
  expression?: string;
  /**
   * @remarks
   * The rule ID.
   * 
   * @example
   * 900029
   */
  id?: number;
  /**
   * @remarks
   * The timestamp when the rule was last updated. Unit: milliseconds.
   * 
   * @example
   * 1614674401000
   */
  modifiedTimestamp?: number;
  /**
   * @remarks
   * The description of the rule.
   * 
   * @example
   * describe
   */
  ruleDesc?: string;
  /**
   * @remarks
   * The rule name.
   * 
   * @example
   * auto_test_rule
   */
  ruleName?: string;
  /**
   * @remarks
   * The tagging content.
   * 
   * @example
   * {\\"tagId\\":4577447}
   */
  tagContext?: string;
  /**
   * @remarks
   * The tagging type. Valid values:
   * - **group**: group.
   * - **tag**: label.
   * 
   * @example
   * group
   */
  tagType?: string;
  static names(): { [key: string]: string } {
    return {
      aliUid: 'AliUid',
      createTimestamp: 'CreateTimestamp',
      expression: 'Expression',
      id: 'Id',
      modifiedTimestamp: 'ModifiedTimestamp',
      ruleDesc: 'RuleDesc',
      ruleName: 'RuleName',
      tagContext: 'TagContext',
      tagType: 'TagType',
    };
  }

  static types(): { [key: string]: any } {
    return {
      aliUid: 'number',
      createTimestamp: 'number',
      expression: 'string',
      id: 'number',
      modifiedTimestamp: 'number',
      ruleDesc: 'string',
      ruleName: 'string',
      tagContext: 'string',
      tagType: 'string',
    };
  }

  validate() {
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

export class ListAutoTagRulesResponseBodyPageInfo extends $dara.Model {
  /**
   * @remarks
   * The number of entries on the current page in a paging query.
   * 
   * @example
   * 2
   */
  count?: number;
  /**
   * @remarks
   * The page number of the current page in a paging query.
   * 
   * @example
   * 1
   */
  currentPage?: number;
  /**
   * @remarks
   * The maximum number of entries per page in a paging query.
   * 
   * @example
   * 20
   */
  pageSize?: number;
  /**
   * @remarks
   * The total number of entries.
   * 
   * @example
   * 196
   */
  totalCount?: number;
  static names(): { [key: string]: string } {
    return {
      count: 'Count',
      currentPage: 'CurrentPage',
      pageSize: 'PageSize',
      totalCount: 'TotalCount',
    };
  }

  static types(): { [key: string]: any } {
    return {
      count: 'number',
      currentPage: 'number',
      pageSize: 'number',
      totalCount: 'number',
    };
  }

  validate() {
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

export class ListAutoTagRulesResponseBody extends $dara.Model {
  /**
   * @remarks
   * The list of rules.
   */
  autoTagRuleList?: ListAutoTagRulesResponseBodyAutoTagRuleList[];
  /**
   * @remarks
   * The pagination information.
   */
  pageInfo?: ListAutoTagRulesResponseBodyPageInfo;
  /**
   * @remarks
   * The request ID, which is a unique identifier generated by Alibaba Cloud for the request. You can use this ID to troubleshoot issues.
   * 
   * @example
   * 1383B0DB-D5D6-4B0C-9E6B-75939C8E67FE
   */
  requestId?: string;
  static names(): { [key: string]: string } {
    return {
      autoTagRuleList: 'AutoTagRuleList',
      pageInfo: 'PageInfo',
      requestId: 'RequestId',
    };
  }

  static types(): { [key: string]: any } {
    return {
      autoTagRuleList: { 'type': 'array', 'itemType': ListAutoTagRulesResponseBodyAutoTagRuleList },
      pageInfo: ListAutoTagRulesResponseBodyPageInfo,
      requestId: 'string',
    };
  }

  validate() {
    if(Array.isArray(this.autoTagRuleList)) {
      $dara.Model.validateArray(this.autoTagRuleList);
    }
    if(this.pageInfo && typeof (this.pageInfo as any).validate === 'function') {
      (this.pageInfo as any).validate();
    }
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

