// This file is auto-generated, don't edit it
import * as $dara from '@darabonba/typescript';


export class UpdateCheckPolicyResponseBodyCheckCustomPolicy extends $dara.Model {
  /**
   * @remarks
   * ID of the custom policy.
   * 
   * @example
   * 100000000001
   */
  policyId?: number;
  /**
   * @remarks
   * Name of the custom policy.
   * 
   * @example
   * testPolictName
   */
  policyShowName?: string;
  /**
   * @remarks
   * Policy type of the custom check item rule:
   * - **STANDARD**: Standard policy type.
   * - **REQUIREMENT**: Requirement policy type.
   * - **SECTION**: Section policy type.
   * 
   * @example
   * STANDARD
   */
  policyType?: string;
  static names(): { [key: string]: string } {
    return {
      policyId: 'PolicyId',
      policyShowName: 'PolicyShowName',
      policyType: 'PolicyType',
    };
  }

  static types(): { [key: string]: any } {
    return {
      policyId: 'number',
      policyShowName: 'string',
      policyType: 'string',
    };
  }

  validate() {
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

export class UpdateCheckPolicyResponseBody extends $dara.Model {
  /**
   * @remarks
   * Details of the custom policy.
   */
  checkCustomPolicy?: UpdateCheckPolicyResponseBodyCheckCustomPolicy;
  /**
   * @remarks
   * The ID of this request, a unique identifier generated by Alibaba Cloud for this request, which can be used for troubleshooting and problem localization.
   * 
   * @example
   * 7532B7EE-7CE7-5F4D-BF04-B12447DD****
   */
  requestId?: string;
  static names(): { [key: string]: string } {
    return {
      checkCustomPolicy: 'CheckCustomPolicy',
      requestId: 'RequestId',
    };
  }

  static types(): { [key: string]: any } {
    return {
      checkCustomPolicy: UpdateCheckPolicyResponseBodyCheckCustomPolicy,
      requestId: 'string',
    };
  }

  validate() {
    if(this.checkCustomPolicy && typeof (this.checkCustomPolicy as any).validate === 'function') {
      (this.checkCustomPolicy as any).validate();
    }
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

