// This file is auto-generated, don't edit it
import * as $dara from '@darabonba/typescript';


export class UpdatePostPaidBindRelResponseBody extends $dara.Model {
  /**
   * @remarks
   * Number of servers successfully bound
   * 
   * @example
   * 2
   */
  bindCount?: number;
  /**
   * @remarks
   * The ID of this request, a unique identifier generated by Alibaba Cloud for this request, which can be used for troubleshooting and problem localization.
   * 
   * @example
   * 09969D2C-4FAD-429E-BFBF-9A60DEF8BF6F
   */
  requestId?: string;
  /**
   * @remarks
   * Binding result status code. Values:
   * 
   * - **0**: Success
   * - **1**: Parameter error
   * - **2**: Insufficient server authorization count
   * - **3**: Insufficient server core authorization
   * - **4**: Postpaid not enabled
   * - **5**: Service suspended due to arrears
   * - **6**: Serverless protection not enabled
   * - **7**: Pay-as-you-go service for host and container security not enabled
   * - **-1**: Binding exception
   * 
   * @example
   * 0
   */
  resultCode?: number;
  static names(): { [key: string]: string } {
    return {
      bindCount: 'BindCount',
      requestId: 'RequestId',
      resultCode: 'ResultCode',
    };
  }

  static types(): { [key: string]: any } {
    return {
      bindCount: 'number',
      requestId: 'string',
      resultCode: 'number',
    };
  }

  validate() {
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

