// This file is auto-generated, don't edit it
import * as $dara from '@darabonba/typescript';


export class CreateOrderRequest extends $dara.Model {
  /**
   * @remarks
   * The client token that is used to ensure the idempotence of the request. This parameter value is generated by the client and must be unique across different requests. The value can be up to 64 ASCII characters in length.
   * 
   * This parameter is required.
   * 
   * @example
   * 2709c68a-d569-4819-9c5d-1222ed2ee924
   */
  clientToken?: string;
  /**
   * @remarks
   * The commodity information of the order. 
   * 
   * You can serialize the corresponding commodity based on the specified OrderType.
   * 
   * The CommodityType values that correspond to different OrderType values are as follows: 
   * * INSTANC_BUY: InstanceBuyCommodity
   * * INSTANCE_RENEW: InstanceRenewCommodity
   * * INSTANCE_UPGRADE: InstanceUpgradeCommodity
   * 
   * The metric description of the Commodity parameter in the example is as follows:
   * - Required parameters
   *   - productCode: the commodity code.
   *   - skuCode: the commodity specification code. Set this parameter to prepay for upfront or postpay for pay-as-you-go.
   *   - duration: the number of periods, such as 1, 2, or 3.
   *   - pricingCycle: the period unit. Valid values: Day, Month, and Year.
   *   - components: the specification modules. The package_version parameter is required. Other modules depend on the commodity settings.
   * 
   * - Optional parameters
   *   - quantity: the quantity to purchase.
   *   - queryPromotion: specifies whether to query promotions.
   *   - couponId: the coupon ID.
   *   - properties: the order extension property string in JSON dict format. Pass parameter values in this field as needed.
   * 
   * This parameter is required.
   * 
   * @example
   * InstanceBuyCommodity示例：{"components":{"package_version":"yuncode1394000000"},"duration":100,"pricingCycle":"Year","productCode":"cmfw019940","properties":{},"quantity":1,"skuCode":"cmfw019940-prepay"}；InstanceRenewCommodity示例：{“components”:{“package_version”:”yuncode1806900001”},”quantity”:1,”duration”:2,”instanceId”:”6227091”,”productCode”:”cmgj024069”,”pricingCycle”:”Month”,”properties”:{},”skuCode”:”cmgj024069-prepay”}；InstanceUpgradeCommodity示例：{“components”:{“package_version”:”yuncode1806900002”},”quantity”:1,”duration”:1,”instanceId”:”6227091”,”productCode”:”cmgj024069”,”pricingCycle”:”Month”,”properties”:{},”skuCode”:”cmgj024069-prepay”}
   */
  commodity?: string;
  /**
   * @remarks
   * The order source. This parameter is not in use.
   * 
   * @example
   * abc
   */
  orderSouce?: string;
  /**
   * @remarks
   * The order type. Valid values: 
   * - INSTANCE_BUY: purchase a product. 
   * - INSTANCE_RENEW: renew an instance. 
   * - INSTANCE_UPGRADE: upgrade an instance.
   * 
   * This parameter is required.
   * 
   * @example
   * INSTANCE_BUY
   */
  orderType?: string;
  ownerId?: string;
  /**
   * @remarks
   * The payment method. Valid values:
   * * AUTO: automatic payment from the account balance.
   * * HAND: manual payment.
   * 
   * This parameter is required.
   * 
   * @example
   * HAND
   */
  paymentType?: string;
  static names(): { [key: string]: string } {
    return {
      clientToken: 'ClientToken',
      commodity: 'Commodity',
      orderSouce: 'OrderSouce',
      orderType: 'OrderType',
      ownerId: 'OwnerId',
      paymentType: 'PaymentType',
    };
  }

  static types(): { [key: string]: any } {
    return {
      clientToken: 'string',
      commodity: 'string',
      orderSouce: 'string',
      orderType: 'string',
      ownerId: 'string',
      paymentType: 'string',
    };
  }

  validate() {
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

