// This file is auto-generated, don't edit it
import * as $dara from '@darabonba/typescript';
import { ListDataQualityResultsResponseBodyPagingInfoDataQualityResultsDetails } from "./ListDataQualityResultsResponseBodyPagingInfoDataQualityResultsDetails";
import { ListDataQualityResultsResponseBodyPagingInfoDataQualityResultsRule } from "./ListDataQualityResultsResponseBodyPagingInfoDataQualityResultsRule";


export class ListDataQualityResultsResponseBodyPagingInfoDataQualityResults extends $dara.Model {
  /**
   * @remarks
   * The time when the data quality check result was generated.
   * 
   * @example
   * 1708284916414
   */
  createTime?: number;
  /**
   * @remarks
   * The information about the data quality check.
   */
  details?: ListDataQualityResultsResponseBodyPagingInfoDataQualityResultsDetails[];
  /**
   * @remarks
   * The ID of the check result.
   * 
   * @example
   * 16033
   */
  id?: number;
  /**
   * @remarks
   * The snapshot of the rule configuration when the check starts.
   */
  rule?: ListDataQualityResultsResponseBodyPagingInfoDataQualityResultsRule;
  /**
   * @remarks
   * The sample values used for the check.
   * 
   * @example
   * [
   *   {
   *     "gender": "male",
   *     "_count": 100
   *   }, {
   *     "gender": "female",
   *     "_count": 100
   *   }
   * ]
   */
  sample?: string;
  /**
   * @remarks
   * The status of the check result. Valid values:
   * 
   * *   Running
   * *   Error
   * *   Passed
   * *   Warned
   * *   Critical
   * 
   * @example
   * PASSED
   */
  status?: string;
  /**
   * @remarks
   * The ID of the instance generated by the check.
   * 
   * @example
   * 200001
   */
  taskInstanceId?: number;
  static names(): { [key: string]: string } {
    return {
      createTime: 'CreateTime',
      details: 'Details',
      id: 'Id',
      rule: 'Rule',
      sample: 'Sample',
      status: 'Status',
      taskInstanceId: 'TaskInstanceId',
    };
  }

  static types(): { [key: string]: any } {
    return {
      createTime: 'number',
      details: { 'type': 'array', 'itemType': ListDataQualityResultsResponseBodyPagingInfoDataQualityResultsDetails },
      id: 'number',
      rule: ListDataQualityResultsResponseBodyPagingInfoDataQualityResultsRule,
      sample: 'string',
      status: 'string',
      taskInstanceId: 'number',
    };
  }

  validate() {
    if(Array.isArray(this.details)) {
      $dara.Model.validateArray(this.details);
    }
    if(this.rule && typeof (this.rule as any).validate === 'function') {
      (this.rule as any).validate();
    }
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

