// This file is auto-generated, don't edit it
import * as $dara from '@darabonba/typescript';


export class GetStackRequest extends $dara.Model {
  /**
   * @remarks
   * The client token that is used to ensure the idempotence of the request. The token is generated by the client and must be globally unique.  
   * The token can be up to 64 characters in length.   
   * For more information, see [How to ensure idempotence](https://help.aliyun.com/document_detail/134212.html).
   * 
   * @example
   * 123e4567-e89b-12d3-a456-42665544****
   */
  clientToken?: string;
  /**
   * @remarks
   * The log option. Valid values:
   * - None: Does not return logs.
   * - Stack (default): Returns stack-related logs.
   * - Resource: Returns resource-related logs.
   * - All: Returns all logs.
   * 
   * @example
   * Stack
   */
  logOption?: string;
  /**
   * @remarks
   * Specifies whether to return the Outputs parameter (the list of stack outputs). Valid values:  
   * 
   * - Enabled (default): Returns the Outputs parameter.  
   * 
   * - Disabled: Does not return the Outputs parameter.  
   * > Computing Outputs is time-consuming. If you do not need the Outputs information, set OutputOption to Disabled to improve the response speed of the API.
   * 
   * @example
   * Disabled
   */
  outputOption?: string;
  /**
   * @remarks
   * The region ID of the stack. You can call [DescribeRegions](https://help.aliyun.com/document_detail/131035.html) to query the most recent region list.
   * 
   * This parameter is required.
   * 
   * @example
   * cn-hangzhou
   */
  regionId?: string;
  /**
   * @remarks
   * Specifies whether to return the ResourceProgress parameter (resource processing progress). Valid values:  
   * 
   * - Disabled (default): Does not return the ResourceProgress parameter.
   * 
   * - PercentageOnly: Returns the StackOperationProgress and StackActionProgress parameters in ResourceProgress.
   * 
   * > Both ROS stacks and Terraform stacks are supported. Stack creation (including continued creation), update, deletion, resource import, and corresponding rollback operations are supported.
   * 
   * - EnabledIfCreateStack (not recommended): Returns the *Count and InProgressResourceDetails parameters in ResourceProgress only during stack creation.  
   * > During stack creation, the stack status is CREATE_IN_PROGRESS, CREATE_COMPLETE, CREATE_FAILED, CREATE_ROLLBACK_IN_PROGRESS, CREATE_ROLLBACK_COMPLETE, or CREATE_ROLLBACK_FAILED.
   * 
   * @example
   * Disabled
   */
  showResourceProgress?: string;
  /**
   * @remarks
   * The stack ID.
   * 
   * This parameter is required.
   * 
   * @example
   * c754d2a4-28f1-46df-b557-9586173a****
   */
  stackId?: string;
  static names(): { [key: string]: string } {
    return {
      clientToken: 'ClientToken',
      logOption: 'LogOption',
      outputOption: 'OutputOption',
      regionId: 'RegionId',
      showResourceProgress: 'ShowResourceProgress',
      stackId: 'StackId',
    };
  }

  static types(): { [key: string]: any } {
    return {
      clientToken: 'string',
      logOption: 'string',
      outputOption: 'string',
      regionId: 'string',
      showResourceProgress: 'string',
      stackId: 'string',
    };
  }

  validate() {
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

