// This file is auto-generated, don't edit it
import * as $dara from '@darabonba/typescript';


export class DeletePlaybookResponseBody extends $dara.Model {
  /**
   * @remarks
   * The ID of this call request, which is a unique identifier generated by Alibaba Cloud for this request, and can be used for troubleshooting and problem localization.
   * 
   * @example
   * 6F3CA8A9-B5BB-506A-9182-FFE80A6E0584
   */
  requestId?: string;
  static names(): { [key: string]: string } {
    return {
      requestId: 'RequestId',
    };
  }

  static types(): { [key: string]: any } {
    return {
      requestId: 'string',
    };
  }

  validate() {
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

