// This file is auto-generated, don't edit it
import * as $dara from '@darabonba/typescript';


export class UpdatePlaybookResponseBody extends $dara.Model {
  /**
   * @remarks
   * UUID of the playbook.
   * 
   * @example
   * 8f55e76d-b5d5-4720-9cd7-xxxxx
   */
  playbookUuid?: string;
  /**
   * @remarks
   * The ID of this request, which is a unique identifier generated by Alibaba Cloud for the request, and can be used for troubleshooting and problem localization.
   * 
   * @example
   * 1A01B0BA-****-5813-****-A5DA15FA95AE
   */
  requestId?: string;
  static names(): { [key: string]: string } {
    return {
      playbookUuid: 'PlaybookUuid',
      requestId: 'RequestId',
    };
  }

  static types(): { [key: string]: any } {
    return {
      playbookUuid: 'string',
      requestId: 'string',
    };
  }

  validate() {
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

