// This file is auto-generated, don't edit it
import * as $dara from '@darabonba/typescript';


export class DescribeOpenApiListResponseBodyData extends $dara.Model {
  /**
   * @remarks
   * The response code. Values:
   * 
   * - 200: Success
   * 
   * - 500: Failed
   * 
   * @example
   * 200
   */
  code?: string;
  /**
   * @remarks
   * The returned API list content.
   * 
   * @example
   * [{"apis":[{"summary":"get account information","deprecated":false,"name":"DescAccountSummary","title":"get account information"}],"childrens":[],"title":"account"}]
   */
  directories?: any;
  /**
   * @remarks
   * The API version number.
   * 
   * @example
   * 2018-12-03
   */
  version?: string;
  /**
   * @remarks
   * List of supported versions.
   * 
   * @example
   * ["2018-12-03" ]
   */
  versions?: any;
  static names(): { [key: string]: string } {
    return {
      code: 'Code',
      directories: 'Directories',
      version: 'Version',
      versions: 'Versions',
    };
  }

  static types(): { [key: string]: any } {
    return {
      code: 'string',
      directories: 'any',
      version: 'string',
      versions: 'any',
    };
  }

  validate() {
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

export class DescribeOpenApiListResponseBody extends $dara.Model {
  /**
   * @remarks
   * Returned result data.
   */
  data?: DescribeOpenApiListResponseBodyData;
  /**
   * @remarks
   * The ID of this request, a unique identifier generated by Alibaba Cloud for this request, used for troubleshooting and locating issues.
   * 
   * @example
   * EF2ECA2D-D8E6-5021-BF5C-19DD6D52C5B2
   */
  requestId?: string;
  static names(): { [key: string]: string } {
    return {
      data: 'Data',
      requestId: 'RequestId',
    };
  }

  static types(): { [key: string]: any } {
    return {
      data: DescribeOpenApiListResponseBodyData,
      requestId: 'string',
    };
  }

  validate() {
    if(this.data && typeof (this.data as any).validate === 'function') {
      (this.data as any).validate();
    }
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

