// This file is auto-generated, don't edit it
import * as $dara from '@darabonba/typescript';


export class DescribeExecutePlaybooksResponseBodyPlaybookMetrics extends $dara.Model {
  /**
   * @remarks
   * The description of the playbook.
   * 
   * @example
   * a demo playbook
   */
  description?: string;
  /**
   * @remarks
   * The name of the playbook.
   * 
   * @example
   * demo_playbook
   */
  displayName?: string;
  /**
   * @remarks
   * The configuration of the input parameters for the playbook. The value is in the JSONArray format.
   * 
   * > For more information about the format, see the [DescribePlaybookInputOutput](~~DescribePlaybookInputOutput~~) operation.
   * 
   * @example
   * [
   *     {
   *         "typeName": "String",
   *         "dataClass": "normal",
   *         "dataType": "String",
   *         "description": "period",
   *         "example": "",
   *         "name": "period",
   *         "required": false
   *     }
   * ]
   */
  paramConfig?: string;
  /**
   * @remarks
   * The type of the input parameter for the playbook.
   * 
   * - **template-ip**: IP request template.
   * 
   * - **template-file**: file request template.
   * 
   * - **template-process**: process request template.
   * 
   * - **custom**: custom parameter.
   * 
   * @example
   * custom
   */
  paramType?: string;
  /**
   * @remarks
   * The UUID of the playbook.
   * 
   * @example
   * c5c88b5e-97ca-435d-8c20-2xxxxx
   */
  uuid?: string;
  static names(): { [key: string]: string } {
    return {
      description: 'Description',
      displayName: 'DisplayName',
      paramConfig: 'ParamConfig',
      paramType: 'ParamType',
      uuid: 'Uuid',
    };
  }

  static types(): { [key: string]: any } {
    return {
      description: 'string',
      displayName: 'string',
      paramConfig: 'string',
      paramType: 'string',
      uuid: 'string',
    };
  }

  validate() {
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

export class DescribeExecutePlaybooksResponseBody extends $dara.Model {
  /**
   * @remarks
   * The list of playbooks.
   */
  playbookMetrics?: DescribeExecutePlaybooksResponseBodyPlaybookMetrics[];
  /**
   * @remarks
   * The ID of the request. This ID is unique to the request and is generated by Alibaba Cloud. Use this ID to troubleshoot issues.
   * 
   * @example
   * 88A39217-2802-5B1E-BA2B-CF1BBC43C1F5
   */
  requestId?: string;
  static names(): { [key: string]: string } {
    return {
      playbookMetrics: 'PlaybookMetrics',
      requestId: 'RequestId',
    };
  }

  static types(): { [key: string]: any } {
    return {
      playbookMetrics: { 'type': 'array', 'itemType': DescribeExecutePlaybooksResponseBodyPlaybookMetrics },
      requestId: 'string',
    };
  }

  validate() {
    if(Array.isArray(this.playbookMetrics)) {
      $dara.Model.validateArray(this.playbookMetrics);
    }
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

