// This file is auto-generated, don't edit it
import * as $dara from '@darabonba/typescript';
import { AddressGroup } from "./AddressGroup";
import { PAL7Config } from "./Pal7config";
import { PAApplicationUnauthorizedAccessConfig } from "./PaapplicationUnauthorizedAccessConfig";


export class GetPrivateAccessApplicationResponseBodyApplicationPortRanges extends $dara.Model {
  /**
   * @remarks
   * The start port.
   * 
   * @example
   * 80
   */
  begin?: number;
  /**
   * @remarks
   * The end port.
   * 
   * @example
   * 81
   */
  end?: number;
  static names(): { [key: string]: string } {
    return {
      begin: 'Begin',
      end: 'End',
    };
  }

  static types(): { [key: string]: any } {
    return {
      begin: 'number',
      end: 'number',
    };
  }

  validate() {
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

export class GetPrivateAccessApplicationResponseBodyApplication extends $dara.Model {
  /**
   * @remarks
   * The application address groups. This parameter is required when ConfigMode is set to Precise and cannot be specified when ConfigMode is set to an empty string.
   */
  addressGroups?: AddressGroup[];
  /**
   * @remarks
   * The addresses of the internal-facing access application.
   */
  addresses?: string[];
  /**
   * @remarks
   * The ID of the internal-facing access application.
   * 
   * @example
   * pa-application-e12860ef6c48****
   */
  applicationId?: string;
  /**
   * @remarks
   * Indicates whether the application is automatically generated by a cloud application.
   * 
   * @example
   * false
   */
  autoGenerated?: number;
  /**
   * @remarks
   * The browser access mode. Valid values:
   * - **Enabled**: enabled.
   * - **Disabled**: disabled.
   * 
   * @example
   * Enabled
   */
  browserAccessStatus?: string;
  /**
   * @remarks
   * The configuration mode. Valid values:
   * * Empty string: default mode.
   * * Precise: precise mode.
   * 
   * @example
   * Precise
   */
  configMode?: string;
  /**
   * @remarks
   * The connector IDs.
   */
  connectorIds?: string[];
  /**
   * @remarks
   * The time when the internal-facing access application was created.
   * 
   * @example
   * 2022-08-30 16:50:32
   */
  createTime?: string;
  /**
   * @remarks
   * The description of the internal-facing access application.
   * 
   * @example
   * 这是一条内网访问应用
   */
  description?: string;
  /**
   * @remarks
   * The browser access mode parameter: application configuration.
   */
  l7Config?: PAL7Config;
  /**
   * @remarks
   * The browser access mode parameter: mapped proxy domain name.
   * 
   * @example
   * app.example.com
   */
  l7ProxyDomainAutomatic?: string;
  /**
   * @remarks
   * The browser access mode parameter: custom proxy domain name.
   * 
   * @example
   * app.example.com
   */
  l7ProxyDomainCustom?: string;
  /**
   * @remarks
   * The name of the internal-facing access application.
   * 
   * @example
   * private_access_application_name
   */
  name?: string;
  /**
   * @remarks
   * The IDs of the internal-facing access policies.
   */
  policyIds?: string[];
  /**
   * @remarks
   * The port ranges of the internal-facing access application. Multiple port ranges cannot be duplicate or overlapping.
   */
  portRanges?: GetPrivateAccessApplicationResponseBodyApplicationPortRanges[];
  /**
   * @remarks
   * The protocol of the internal-facing access application. Valid values:
   * - **All**: all protocols.
   * - **TCP**.
   * - **UDP**.
   * 
   * @example
   * All
   */
  protocol?: string;
  /**
   * @remarks
   * The status of the internal-facing access application. Valid values:
   * - **Enabled**: enabled.
   * - **Disabled**: disabled.
   * 
   * @example
   * Enabled
   */
  status?: string;
  /**
   * @remarks
   * The IDs of the internal-facing access tags.
   */
  tagIds?: string[];
  /**
   * @remarks
   * The configuration for unauthorized application access requests.
   */
  unauthorizedAccessConfig?: PAApplicationUnauthorizedAccessConfig;
  static names(): { [key: string]: string } {
    return {
      addressGroups: 'AddressGroups',
      addresses: 'Addresses',
      applicationId: 'ApplicationId',
      autoGenerated: 'AutoGenerated',
      browserAccessStatus: 'BrowserAccessStatus',
      configMode: 'ConfigMode',
      connectorIds: 'ConnectorIds',
      createTime: 'CreateTime',
      description: 'Description',
      l7Config: 'L7Config',
      l7ProxyDomainAutomatic: 'L7ProxyDomainAutomatic',
      l7ProxyDomainCustom: 'L7ProxyDomainCustom',
      name: 'Name',
      policyIds: 'PolicyIds',
      portRanges: 'PortRanges',
      protocol: 'Protocol',
      status: 'Status',
      tagIds: 'TagIds',
      unauthorizedAccessConfig: 'UnauthorizedAccessConfig',
    };
  }

  static types(): { [key: string]: any } {
    return {
      addressGroups: { 'type': 'array', 'itemType': AddressGroup },
      addresses: { 'type': 'array', 'itemType': 'string' },
      applicationId: 'string',
      autoGenerated: 'number',
      browserAccessStatus: 'string',
      configMode: 'string',
      connectorIds: { 'type': 'array', 'itemType': 'string' },
      createTime: 'string',
      description: 'string',
      l7Config: PAL7Config,
      l7ProxyDomainAutomatic: 'string',
      l7ProxyDomainCustom: 'string',
      name: 'string',
      policyIds: { 'type': 'array', 'itemType': 'string' },
      portRanges: { 'type': 'array', 'itemType': GetPrivateAccessApplicationResponseBodyApplicationPortRanges },
      protocol: 'string',
      status: 'string',
      tagIds: { 'type': 'array', 'itemType': 'string' },
      unauthorizedAccessConfig: PAApplicationUnauthorizedAccessConfig,
    };
  }

  validate() {
    if(Array.isArray(this.addressGroups)) {
      $dara.Model.validateArray(this.addressGroups);
    }
    if(Array.isArray(this.addresses)) {
      $dara.Model.validateArray(this.addresses);
    }
    if(Array.isArray(this.connectorIds)) {
      $dara.Model.validateArray(this.connectorIds);
    }
    if(this.l7Config && typeof (this.l7Config as any).validate === 'function') {
      (this.l7Config as any).validate();
    }
    if(Array.isArray(this.policyIds)) {
      $dara.Model.validateArray(this.policyIds);
    }
    if(Array.isArray(this.portRanges)) {
      $dara.Model.validateArray(this.portRanges);
    }
    if(Array.isArray(this.tagIds)) {
      $dara.Model.validateArray(this.tagIds);
    }
    if(this.unauthorizedAccessConfig && typeof (this.unauthorizedAccessConfig as any).validate === 'function') {
      (this.unauthorizedAccessConfig as any).validate();
    }
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

export class GetPrivateAccessApplicationResponseBody extends $dara.Model {
  /**
   * @remarks
   * The internal-facing access application.
   */
  application?: GetPrivateAccessApplicationResponseBodyApplication;
  /**
   * @remarks
   * The request ID.
   * 
   * @example
   * 3ACC5EDC-2B7D-5032-8C58-D7615D66C1D4
   */
  requestId?: string;
  static names(): { [key: string]: string } {
    return {
      application: 'Application',
      requestId: 'RequestId',
    };
  }

  static types(): { [key: string]: any } {
    return {
      application: GetPrivateAccessApplicationResponseBodyApplication,
      requestId: 'string',
    };
  }

  validate() {
    if(this.application && typeof (this.application as any).validate === 'function') {
      (this.application as any).validate();
    }
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

