// This file is auto-generated, don't edit it
import * as $dara from '@darabonba/typescript';


export class DeleteUserCertificateRequest extends $dara.Model {
  /**
   * @remarks
   * The certificate ID.
   * > You can call [ListUserCertificateOrder](https://help.aliyun.com/document_detail/455804.html) to obtain the ID.
   * 
   * This parameter is required.
   * 
   * @example
   * 7562353
   */
  certId?: number;
  /**
   * @remarks
   * The client token that is used to ensure the idempotence of the request. The value of this parameter is generated by the client and must be unique among different requests. The value can be up to 64 characters in length and cannot contain non-ASCII characters.
   * 
   * @example
   * XXX
   */
  clientToken?: string;
  static names(): { [key: string]: string } {
    return {
      certId: 'CertId',
      clientToken: 'ClientToken',
    };
  }

  static types(): { [key: string]: any } {
    return {
      certId: 'number',
      clientToken: 'string',
    };
  }

  validate() {
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

