// This file is auto-generated, don't edit it
import * as $dara from '@darabonba/typescript';


export class DescribeGlobalDesktopsRequest extends $dara.Model {
  /**
   * @remarks
   * The unique ID generated by the client.
   * 
   * This parameter is required.
   * 
   * @example
   * c213150d-7ac3-432c-b749-6e1e090b****
   */
  clientId?: string;
  /**
   * @remarks
   * The method that is used to connect cloud computers that reside in the office network from WUYING clients.
   * 
   * >  The VPC connection method depends on Alibaba Cloud PrivateLink. You can use PrivateLink for free. If you set this parameter to VPC or Any, the system automatically enables PrivateLink.
   * 
   * Valid values:
   * 
   * *   INTERNET (default): End users connect to cloud computers from clients over the Internet.
   * *   VPC: End users connect to cloud computers from clients over a virtual private cloud (VPC).
   * *   Any: End users connect to cloud computers from clients over the Internet or a VPC.
   * 
   * @example
   * INTERNET
   */
  desktopAccessType?: string;
  /**
   * @remarks
   * The cloud computer ID. You can specify one or more cloud computer IDs. Valid values: 1 to 20.
   */
  desktopId?: string[];
  /**
   * @remarks
   * The cloud computer name.
   * 
   * @example
   * DesktopTest
   */
  desktopName?: string;
  /**
   * @remarks
   * The cloud computer status.
   * 
   * Valid value:
   * 
   * *   Stopped
   * *   Starting.
   * *   Rebuilding
   * *   Running:.
   * *   Stopping:.
   * *   Expired
   * *   Deleted
   * *   Pending: The resource is still being prepared.
   * 
   * @example
   * Running
   */
  desktopStatus?: string;
  /**
   * @remarks
   * The office network IDs.
   * 
   * >  This parameter is about to be disabled. Use `OfficeSiteId`.
   * 
   * @example
   * cn-hangzhou+dir-880841****
   */
  directoryId?: string;
  /**
   * @remarks
   * The keyword. Fuzzy search is supported for cloud computer IDs, cloud computer names, and end user custom cloud computer names.
   * 
   * @example
   * ecd
   */
  keyword?: string;
  language?: string;
  /**
   * @remarks
   * The ID of the region where the office network resides. This parameter is left empty when you log on with an organization ID.
   * 
   * *   This parameter is required when you log on by using the office network ID.
   * *   If you log on by using an organization ID, this parameter can be left empty.
   * 
   * @example
   * cn-hangzhou
   */
  loginRegionId?: string;
  /**
   * @remarks
   * The logon token. You can call the GetLoginToken operation to obtain the token. You can also call the UpdateToken operation to obtain the token RefreshLoginToken. Response parameter: LoginToken.
   * 
   * This parameter is required.
   * 
   * @example
   * v147c9114a180489f89691663893169****
   */
  loginToken?: string;
  /**
   * @remarks
   * The number of entries per page.
   * 
   * *   Maximum value: 500.
   * *   and the default value is 10.
   * 
   * @example
   * 500
   */
  maxResults?: number;
  /**
   * @remarks
   * The token used to start the next query. If NextToken is empty, it indicates that there is no next query.
   * 
   * @example
   * eyJkZWZhdWx0IjpbIjk2MjEy****
   */
  nextToken?: string;
  /**
   * @remarks
   * The office network IDs.
   * 
   * >  `DirectoryId` the parameter is about to be retired, use this field.
   * 
   * @example
   * cn-hangzhou+dir-880841****
   */
  officeSiteId?: string;
  /**
   * @remarks
   * The field used for sorting. If you do not specify this option, the system is sorted in descending order of creation time.
   * 
   * Valid values:
   * 
   * *   AssignTime: sort by allocation time.
   * 
   * @example
   * AssignTime
   */
  orderBy?: string;
  /**
   * @remarks
   * Specifies whether to query information about the image update.
   * 
   * @example
   * true
   */
  queryFotaUpdate?: boolean;
  /**
   * @remarks
   * The region ID.
   * 
   * Valid value:
   * 
   * *   cn-shanghai: China (Shanghai)
   * 
   * @example
   * cn-shanghai
   */
  regionId?: string;
  /**
   * @remarks
   * The ID of the searched region. You can specify this parameter to filter cloud computers in specific regions.
   * 
   * @example
   * cn-shanghai
   */
  searchRegionId?: string;
  /**
   * @remarks
   * The session ID. You can call the GetLoginToken operation to query the value of the SessionId parameter.
   * 
   * @example
   * 5c456a41-1e65-4e72-ab4d-5dcfff52****
   */
  sessionId?: string;
  /**
   * @remarks
   * The sorting method.
   * 
   * Valid values:
   * 
   * *   ASC (default): the ascending order.
   * *   DESC: the descending order.
   * 
   * @example
   * ASC
   */
  sortType?: string;
  /**
   * @remarks
   * Whether to query real-time cloud computer information. The cloud computer status information in the current interface has a delay of 1 to 3 seconds. If you need accurate information, set this value to `true`.
   * 
   * @example
   * true
   */
  withoutLatency?: boolean;
  static names(): { [key: string]: string } {
    return {
      clientId: 'ClientId',
      desktopAccessType: 'DesktopAccessType',
      desktopId: 'DesktopId',
      desktopName: 'DesktopName',
      desktopStatus: 'DesktopStatus',
      directoryId: 'DirectoryId',
      keyword: 'Keyword',
      language: 'Language',
      loginRegionId: 'LoginRegionId',
      loginToken: 'LoginToken',
      maxResults: 'MaxResults',
      nextToken: 'NextToken',
      officeSiteId: 'OfficeSiteId',
      orderBy: 'OrderBy',
      queryFotaUpdate: 'QueryFotaUpdate',
      regionId: 'RegionId',
      searchRegionId: 'SearchRegionId',
      sessionId: 'SessionId',
      sortType: 'SortType',
      withoutLatency: 'WithoutLatency',
    };
  }

  static types(): { [key: string]: any } {
    return {
      clientId: 'string',
      desktopAccessType: 'string',
      desktopId: { 'type': 'array', 'itemType': 'string' },
      desktopName: 'string',
      desktopStatus: 'string',
      directoryId: 'string',
      keyword: 'string',
      language: 'string',
      loginRegionId: 'string',
      loginToken: 'string',
      maxResults: 'number',
      nextToken: 'string',
      officeSiteId: 'string',
      orderBy: 'string',
      queryFotaUpdate: 'boolean',
      regionId: 'string',
      searchRegionId: 'string',
      sessionId: 'string',
      sortType: 'string',
      withoutLatency: 'boolean',
    };
  }

  validate() {
    if(Array.isArray(this.desktopId)) {
      $dara.Model.validateArray(this.desktopId);
    }
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

