// This file is auto-generated, don't edit it
import * as $dara from '@darabonba/typescript';


export class CreateSubCACertificateRequestTags extends $dara.Model {
  /**
   * @remarks
   * The label key.
   * 
   * @example
   * testKey
   */
  key?: string;
  /**
   * @remarks
   * The label value.
   * 
   * @example
   * test
   */
  value?: string;
  static names(): { [key: string]: string } {
    return {
      key: 'Key',
      value: 'Value',
    };
  }

  static types(): { [key: string]: any } {
    return {
      key: 'string',
      value: 'string',
    };
  }

  validate() {
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

export class CreateSubCACertificateRequest extends $dara.Model {
  /**
   * @remarks
   * The key algorithm type of the subordinate CA certificate. The key algorithm is represented in the `<encryption algorithm>_<key length>` format. Valid values:
   * - **RSA_1024**: The corresponding signature algorithm is Sha256WithRSA.
   * - **RSA_2048**: The corresponding signature algorithm is Sha256WithRSA.
   * - **RSA_4096**: The corresponding signature algorithm is Sha256WithRSA.
   * - **ECC_256**: The corresponding signature algorithm is Sha256WithECDSA.
   * - **SM2_256**: The corresponding signature algorithm is SM3WithSM2.
   * 
   * 
   * The encryption algorithm of the subordinate CA certificate must be the same as that of the root CA certificate, but the key length can be different. Example: If the key algorithm of the root CA certificate is **RSA_2048**, the key algorithm of the subordinate CA certificate must be **RSA_1024**, **RSA_2048**, or **RSA_4096**.
   * 
   * > You can invoke [DescribeCACertificate](https://help.aliyun.com/document_detail/465954.html) to query the key algorithm of the root CA certificate.
   * 
   * This parameter is required.
   * 
   * @example
   * RSA_2048
   */
  algorithm?: string;
  /**
   * @remarks
   * The maximum validity period of certificates issued by the CA, specified by the certMaxTime of the CA. Unit: days.
   * 
   * @example
   * 30
   */
  certMaxTime?: number;
  /**
   * @remarks
   * A client token that is used to ensure the idempotence of the request. The value is generated by the client and must be unique across different requests. The parameter value can be up to 64 ASCII characters in length and cannot contain non-ASCII characters.
   * 
   * @example
   * XXX
   */
  clientToken?: string;
  /**
   * @remarks
   * The common name or abbreviation of the organization. Chinese and English characters are supported.
   * 
   * This parameter is required.
   * 
   * @example
   * Aliyun
   */
  commonName?: string;
  /**
   * @remarks
   * The code of the country or region where the organization is located, represented by a two-letter or three-letter uppercase abbreviation. For example, **CN** represents China, and **US** represents the United States.
   * 
   * For the codes of different countries, see the **International codes** section in [Manage company information](https://help.aliyun.com/document_detail/198289.html).
   * 
   * @example
   * CN
   */
  countryCode?: string;
  /**
   * @remarks
   * The validity period of the CRL. Valid values: 1 to 365. Unit: days.
   * 
   * @example
   * 30
   */
  crlDay?: number;
  /**
   * @remarks
   * Specifies whether to enable the CRL service. Valid values:
   * 
   * - false: Disabled.
   * - true: Enabled.
   * 
   * @example
   * true
   */
  enableCrl?: boolean;
  /**
   * @remarks
   * The extension key usages.
   */
  extendedKeyUsages?: string[];
  /**
   * @remarks
   * The name of the city where the organization is located. Chinese and English characters are supported.
   * 
   * This parameter is required.
   * 
   * @example
   * Hangzhou
   */
  locality?: string;
  /**
   * @remarks
   * The name of the organization associated with the subordinate CA certificate (corresponding to your enterprise or entity). Chinese and English characters are supported.
   * 
   * This parameter is required.
   * 
   * @example
   * Alibaba
   */
  organization?: string;
  /**
   * @remarks
   * The name of the department or branch under the organization. Chinese and English characters are supported.
   * 
   * This parameter is required.
   * 
   * @example
   * Security
   */
  organizationUnit?: string;
  /**
   * @remarks
   * The unique identifier of the root CA certificate.
   * 
   * 
   * > You can invoke [DescribeCACertificateList](https://help.aliyun.com/document_detail/465957.html) to query the unique identifiers of all CA certificates.
   * 
   * @example
   * 1a83bcbb89e562885e40aa0108f5****
   */
  parentIdentifier?: string;
  /**
   * @remarks
   * The path length constraint of the certificate. Default value: 0.
   * 
   * @example
   * 0
   */
  pathLenConstraint?: number;
  /**
   * @remarks
   * The resource group ID.
   * 
   * @example
   * rg-ae****vty
   */
  resourceGroupId?: string;
  /**
   * @remarks
   * <props="china">The name of the province, municipality, or autonomous region where the organization is located. Chinese and English characters are supported.
   * <props="intl">The name of the province or state where the organization is located. Chinese and English characters are supported.
   * 
   * This parameter is required.
   * 
   * @example
   * Zhejiang
   */
  state?: string;
  /**
   * @remarks
   * The label list.
   */
  tags?: CreateSubCACertificateRequestTags[];
  /**
   * @remarks
   * The validity period of the subordinate CA certificate. Unit: years.
   * 
   * Set this value to 5 to 10 years.
   * 
   * > The validity period of the subordinate CA certificate cannot exceed that of the root CA certificate. You can invoke [DescribeCACertificate](https://help.aliyun.com/document_detail/465954.html) to query the validity period of the root CA certificate.
   * 
   * This parameter is required.
   * 
   * @example
   * 5
   */
  years?: number;
  static names(): { [key: string]: string } {
    return {
      algorithm: 'Algorithm',
      certMaxTime: 'CertMaxTime',
      clientToken: 'ClientToken',
      commonName: 'CommonName',
      countryCode: 'CountryCode',
      crlDay: 'CrlDay',
      enableCrl: 'EnableCrl',
      extendedKeyUsages: 'ExtendedKeyUsages',
      locality: 'Locality',
      organization: 'Organization',
      organizationUnit: 'OrganizationUnit',
      parentIdentifier: 'ParentIdentifier',
      pathLenConstraint: 'PathLenConstraint',
      resourceGroupId: 'ResourceGroupId',
      state: 'State',
      tags: 'Tags',
      years: 'Years',
    };
  }

  static types(): { [key: string]: any } {
    return {
      algorithm: 'string',
      certMaxTime: 'number',
      clientToken: 'string',
      commonName: 'string',
      countryCode: 'string',
      crlDay: 'number',
      enableCrl: 'boolean',
      extendedKeyUsages: { 'type': 'array', 'itemType': 'string' },
      locality: 'string',
      organization: 'string',
      organizationUnit: 'string',
      parentIdentifier: 'string',
      pathLenConstraint: 'number',
      resourceGroupId: 'string',
      state: 'string',
      tags: { 'type': 'array', 'itemType': CreateSubCACertificateRequestTags },
      years: 'number',
    };
  }

  validate() {
    if(Array.isArray(this.extendedKeyUsages)) {
      $dara.Model.validateArray(this.extendedKeyUsages);
    }
    if(Array.isArray(this.tags)) {
      $dara.Model.validateArray(this.tags);
    }
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

