// This file is auto-generated, don't edit it
import * as $dara from '@darabonba/typescript';


export class CreateExternalCACertificateShrinkRequestTags extends $dara.Model {
  /**
   * @remarks
   * The tag key.
   * 
   * @example
   * database
   */
  key?: string;
  /**
   * @remarks
   * The tag value.
   * 
   * @example
   * 1
   */
  value?: string;
  static names(): { [key: string]: string } {
    return {
      key: 'Key',
      value: 'Value',
    };
  }

  static types(): { [key: string]: any } {
    return {
      key: 'string',
      value: 'string',
    };
  }

  validate() {
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

export class CreateExternalCACertificateShrinkRequest extends $dara.Model {
  /**
   * @remarks
   * Overrides CSR content or adds content to the CA certificate through API parameters.
   */
  apiPassthroughShrink?: string;
  /**
   * @remarks
   * The maximum validity period for issued certificates, as specified by the certMaxTime of the CA. Unit: days.
   * 
   * @example
   * 30
   */
  certMaxTime?: number;
  /**
   * @remarks
   * The certificate signing request. The CSR can contain the SubjectDN and custom extensions of the CA certificate. The SubjectKeyIdentifier, AuthorityKeyIdentifier, and CRLDistributionPoints certificate extensions are generated by the CA, and the values in the CSR are ignored.
   * 
   * @example
   * -----BEGIN CERTIFICATE REQUEST-----
   * MIIBczCCARgCAQAwgYoxFDASBgNVBAMMC2FsaXl1bi50ZXN0MQ0wCwYDVQQ
   * ...
   * vbIgMQIhAKHDWD6/WAMbtezAt4bysJ/BZIDz1jPWuUR5GV4TJ/mS
   * -----END CERTIFICATE REQUEST-----
   */
  csr?: string;
  /**
   * @remarks
   * The instance ID of the external subordinate CA instance to activate.
   * 
   * @example
   * cas_deposit-cn-1234abcd
   */
  instanceId?: string;
  /**
   * @remarks
   * The resource group ID.
   * 
   * @example
   * test
   */
  resourceGroupId?: string;
  /**
   * @remarks
   * The list of tags.
   */
  tags?: CreateExternalCACertificateShrinkRequestTags[];
  /**
   * @remarks
   * The certificate validity period. Both relative time and absolute time are supported.
   * 
   * > Relative time: Supports the units of year, month, and day.
   * 
   * - Year - y
   * - Month - m
   * - Day - d
   * 
   * > Absolute time: Uses GMT time. Format: `yyyy-MM-dd\\"T\\"HH:mm:ss\\"Z\\"`
   * 
   * - Specify the end time - `$NotAfter`
   * - Specify the start time and end time - `$NotBefore/$NotAfter`
   * 
   * @example
   * 10y
   */
  validity?: string;
  static names(): { [key: string]: string } {
    return {
      apiPassthroughShrink: 'ApiPassthrough',
      certMaxTime: 'CertMaxTime',
      csr: 'Csr',
      instanceId: 'InstanceId',
      resourceGroupId: 'ResourceGroupId',
      tags: 'Tags',
      validity: 'Validity',
    };
  }

  static types(): { [key: string]: any } {
    return {
      apiPassthroughShrink: 'string',
      certMaxTime: 'number',
      csr: 'string',
      instanceId: 'string',
      resourceGroupId: 'string',
      tags: { 'type': 'array', 'itemType': CreateExternalCACertificateShrinkRequestTags },
      validity: 'string',
    };
  }

  validate() {
    if(Array.isArray(this.tags)) {
      $dara.Model.validateArray(this.tags);
    }
    super.validate();
  }

  constructor(map?: { [key: string]: any }) {
    super(map);
  }
}

